"""Manifest of tests that require a live server (making real HTTP requests)."""

LIVE_SERVER_TESTS = {
    "tests/test_admin_control_panel_api.py",
    "tests/test_admin_tenants_api.py",
    "tests/test_agency_portal_api.py",
    "tests/test_ari_push_engine.py",
    "tests/test_ari_push_engine_v2.py",
    "tests/test_b2b_api.py",
    "tests/test_b2b_webhooks.py",
    "tests/test_banquet_competitor.py",
    "tests/test_booking_room_move_fix.py",
    "tests/test_bug_fixes_cancel_availability.py",
    "tests/test_business_date_validation.py",
    "tests/test_calendar_features.py",
    "tests/test_calendar_past_dates_and_guests_api.py",
    "tests/test_channel_connections.py",
    "tests/test_channel_health_api.py",
    "tests/test_channel_health_dashboard_v2.py",
    "tests/test_channel_manager_v2.py",
    "tests/test_channel_manager_v2_phase6.py",
    "tests/test_checkout_balance_fix.py",
    "tests/test_ci_load_ruff_verification.py",
    "tests/test_cicd_pipeline_api.py",
    "tests/test_sandbox_simulation_api.py",
}
