from datetime import UTC, datetime

from models.schemas.qr_catalogue import (
    AutoPriority,
    EmptyConfig,
    GuestServiceDepartment,
    GuestServiceItem,
    InputType,
    QuantityConfig,
    TimeConstraints,
)

# A stable, generic default catalogue for QR guest requests.
# It is deep-copied at runtime to prevent accidental mutation.

_NOW = datetime(2026, 1, 1, tzinfo=UTC)

DEFAULT_DEPARTMENTS = [
    GuestServiceDepartment(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        labels={"en": "Housekeeping", "tr": "Kat Hizmetleri", "de": "Zimmerreinigung", "ru": "Уборка", "ar": "خدمة الغرف"},
        icon="sparkles",
        display_order=1,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceDepartment(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        labels={"en": "Maintenance", "tr": "Teknik Servis", "de": "Wartung", "ru": "Ремонт", "ar": "صيانة"},
        icon="wrench",
        display_order=2,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceDepartment(
        tenant_id="default",
        property_id="default",
        department_code="reception",
        labels={"en": "Reception", "tr": "Resepsiyon", "de": "Rezeption", "ru": "Стойка", "ar": "استقبال"},
        icon="bell",
        display_order=3,
        created_at=_NOW,
        updated_at=_NOW,
    ),
]

DEFAULT_SERVICES = [
    # Housekeeping
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        service_code="housekeeping.room_cleaning",
        labels={"en": "Room cleaning", "tr": "Oda temizliği"},
        icon="sparkles",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=1,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        service_code="housekeeping.no_cleaning_today",
        labels={"en": "No cleaning today", "tr": "Bugün temizlik istemiyorum"},
        icon="sparkles",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.low,
        display_order=2,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        service_code="housekeeping.extra_bath_towel",
        labels={"en": "Extra bath towel", "tr": "Ekstra banyo havlusu"},
        icon="shirt",
        input_type=InputType.quantity,
        input_config=QuantityConfig(min=1, max=5, default=1),
        auto_priority=AutoPriority.normal,
        display_order=3,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        service_code="housekeeping.extra_toilet_paper",
        labels={"en": "Extra toilet paper", "tr": "Ekstra tuvalet kağıdı"},
        icon="package",
        input_type=InputType.quantity,
        input_config=QuantityConfig(min=1, max=5, default=1),
        auto_priority=AutoPriority.normal,
        display_order=4,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="housekeeping",
        service_code="housekeeping.extra_slippers",
        labels={"en": "Extra slippers", "tr": "Ekstra terlik"},
        icon="shirt",
        input_type=InputType.quantity,
        input_config=QuantityConfig(min=1, max=5, default=1),
        auto_priority=AutoPriority.normal,
        display_order=5,
        created_at=_NOW,
        updated_at=_NOW,
    ),

    # Technical
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.ac_not_working",
        labels={"en": "Air conditioner not working", "tr": "Klima çalışmıyor"},
        icon="thermometer",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.high,
        display_order=1,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.no_hot_water",
        labels={"en": "No hot water", "tr": "Sıcak su yok"},
        icon="wrench",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.high,
        display_order=2,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.light_not_working",
        labels={"en": "Light not working", "tr": "Lamba çalışmıyor"},
        icon="wrench",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=3,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.television_not_working",
        labels={"en": "Television not working", "tr": "Televizyon çalışmıyor"},
        icon="tv",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=4,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.wifi_problem",
        labels={"en": "Wi-Fi problem", "tr": "Wi-Fi problemi"},
        icon="wifi",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.high,
        display_order=5,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="technical",
        service_code="technical.other_problem",
        labels={"en": "Other technical problem", "tr": "Diğer teknik problem"},
        icon="wrench",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=6,
        created_at=_NOW,
        updated_at=_NOW,
    ),

    # Reception
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="reception",
        service_code="reception.late_checkout",
        labels={"en": "Late checkout request", "tr": "Geç çıkış talebi"},
        icon="bell",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=1,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="reception",
        service_code="reception.wake_up_call",
        labels={"en": "Wake-up call", "tr": "Uyandırma servisi"},
        icon="bell",
        input_type=InputType.time,
        input_config=TimeConstraints(interval_minutes=15),
        auto_priority=AutoPriority.normal,
        display_order=2,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="reception",
        service_code="reception.luggage_assistance",
        labels={"en": "Luggage assistance", "tr": "Bagaj yardımı"},
        icon="bell",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=3,
        created_at=_NOW,
        updated_at=_NOW,
    ),
    GuestServiceItem(
        tenant_id="default",
        property_id="default",
        department_code="reception",
        service_code="reception.contact_reception",
        labels={"en": "Contact reception", "tr": "Resepsiyon ile iletişime geç"},
        icon="message",
        input_type=InputType.one_tap,
        input_config=EmptyConfig(),
        auto_priority=AutoPriority.normal,
        display_order=4,
        created_at=_NOW,
        updated_at=_NOW,
    ),
]

def get_default_catalogue() -> dict:
    """Returns a deep copy of the default catalogue components."""
    # Using model_dump (pydantic v2)
    return {
        "departments": [d.model_dump() for d in DEFAULT_DEPARTMENTS],
        "services": [s.model_dump() for s in DEFAULT_SERVICES],
    }

