// Central navigation configuration for main sidebar/top nav
// Each item maps to a module key from the 3-tier subscription system

// Tier that includes this module by default
// basic = all plans, professional = pro+enterprise, enterprise = enterprise only

// ─── NAV GROUPS for top bar dropdown menus ──────────
export const NAV_GROUPS = [
  {
    id: "operations",
    label: "Operasyon",
    icon: "Hotel",
  },
  {
    id: "reservations",
    label: "Rezervasyon",
    icon: "CalendarCheck",
  },
  {
    id: "finance",
    label: "Finans",
    icon: "DollarSign",
  },
  {
    id: "channels",
    label: "Kanallar",
    icon: "Layers",
  },
  {
    id: "reports",
    label: "Raporlar",
    icon: "BarChart3",
  },
  {
    id: "advanced",
    label: "Gelişmiş",
    icon: "Zap",
  },
  {
    id: "management",
    label: "Yönetim",
    icon: "Settings",
  },
  {
    id: "infrastructure",
    label: "Altyapı",
    icon: "Server",
  },
  {
    id: "admin",
    label: "Sistem",
    icon: "Shield",
  },
];

export const NAV_ITEMS = [
  // ──── STANDALONE (shown as direct buttons) ─────────
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/app/dashboard",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── TEDARİK PAZARI (B2B Supplies Marketplace) ────
  {
    key: "supplies_market",
    label: "Tedarik Pazarı",
    path: "/app/supplies-market",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "procurement",
    label: "Satınalma",
    path: "/app/procurement",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "stock_rehber",
    label: "Stok Rehberi",
    path: "/app/stock-rehber",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "audit_timeline",
    label: "Denetim Zaman Çizelgesi",
    path: "/audit-timeline",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    key: "security_hub",
    label: "Güvenlik",
    path: "/security",
    tier: "basic",
    group: "core",
    // Sayfa route'u infrastructure.js'te ve Altyapı'da görünüyor; üst nav
    // highlight'ı da Altyapı'da olmalı. Önceden "admin" idi → "Yönetim"
    // grubu mavi kalıyordu (navGroups.admin = "Yönetim" i18n).
    navGroup: "infrastructure",
  },
  {
    key: "channels_hub",
    label: "Kanallar Hub",
    path: "/channels",
    tier: "basic",
    group: "core",
    navGroup: "channels",
    // Hub yalnızca tab seçilmediğinde (ya da sub-item'la eşleşmeyen tab'da)
    // aktif görünsün; sub-item seçildiğinde alttaki cm_dashboard /
    // channel_connections / channel_ops aktif olur.
    tabBase: ["/channels", "/app/channels"],
    tabKey: null,
  },
  {
    key: "hr_hub",
    label: "İK",
    path: "/hr",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    // Task #26: acil mesaj kullanımı için adanmış rapor ekranı.
    key: "urgent_message_report",
    label: "Acil Mesaj Raporu",
    path: "/urgent-message-report",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    // Task #35: geri alınan iç mesajlar için adanmış denetim raporu.
    key: "recalled_messages_report",
    label: "Geri Alınan Mesajlar",
    path: "/recalled-messages-report",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    // Task #83: KVKK kapsamında resepsiyonun açtığı kimlik fotoğrafı
    // görüntülemelerini denetim için listeleyen rapor.
    key: "id_photo_view_report",
    label: "Kimlik Fotoğrafı Raporu",
    path: "/id-photo-view-report",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    // Task #86: bekleyen kimlik fotoğraflarını listeleyen ve manuel /
    // KVKK toplu silme yapılabilen resepsiyon paneli.
    key: "id_photo_admin",
    label: "Bekleyen Kimlik Fotoğrafları",
    path: "/id-photo-admin",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    // Task #28: kullanıcı bazında acil mesaj iznini açıp/kapatma sayfası.
    key: "urgent_permission_admin",
    label: "Acil Mesaj İzinleri",
    path: "/admin/urgent-permissions",
    tier: "basic",
    group: "core",
    navGroup: "admin",
  },
  {
    // Task #282: numara -> otel/ajan eşleme yönetimi (operatör ekranı).
    key: "voice_number_mapping",
    label: "Ses Numaraları",
    path: "/admin/voice-numbers",
    tier: "basic",
    group: "core",
    navGroup: "admin",
    requireSuperAdmin: true,
  },

  // ──── OPERATIONS GROUP ─────────────────────────────
  {
    key: "reservation_calendar",
    label: "Takvim",
    path: "/app/reservation-calendar",
    moduleKey: "reservation_calendar",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "pms",
    label: "PMS",
    path: "/app/pms",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "pms_operations",
    label: "PMS Operasyonlar",
    path: "/pms-operations",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
    hidden: true,
  },
  {
    key: "folio_detail",
    label: "Folio Detail",
    path: "/folio-detail",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
    hidden: true,
  },
  {
    key: "housekeeping_status",
    label: "Housekeeping",
    path: "/housekeeping-status",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
  },
  {
    key: "shift_handover",
    label: "Vardiya Devri",
    path: "/shift-handover",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
  },
  {
    key: "early_late_pricing",
    label: "Erken/Geç Çıkış Fiyat",
    path: "/settings/early-late-pricing",
    moduleKey: "pms",
    tier: "basic",
    group: "settings",
    navGroup: "management",
  },
  {
    key: "eod_report",
    label: "Gün Sonu Raporu",
    path: "/eod-report",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
  },
  {
    key: "walkin",
    label: "Walk-in Check-in",
    path: "/walkin",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
  },
  {
    key: "room_map",
    label: "Oda Haritası",
    path: "/room-map",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
  },
  {
    key: "wake_up_calls",
    label: "Uyandırma Cagrisi",
    path: "/wake-up-calls",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "lost_found",
    label: "Kayip Esya",
    path: "/lost-found",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "guest_journey",
    label: "Guest Journey",
    path: "/guest-journey",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "operations",
  },
  {
    key: "operational_events",
    label: "Olay Merkezi",
    path: "/operational-events",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "operations",
  },
  {
    key: "service_recovery",
    label: "Sikayet Yönetimi",
    path: "/service-recovery",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },

  // ──── RESERVATIONS GROUP ───────────────────────────
  {
    key: "group_bookings",
    label: "Grup Rezervasyonları",
    path: "/group-bookings-manage",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "block_management",
    label: "Grup Blok Kontenjanı",
    path: "/block-management",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "deposit_tracking",
    label: "Depozito Takibi",
    path: "/deposit-tracking",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "group_folio",
    label: "Grup Folio",
    path: "/group-folio",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "no_show_analytics",
    label: "No-Show Analitik",
    path: "/no-show-analytics",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "departure_list",
    label: "Bugünün Çıkışları",
    path: "/departure-list",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "no_show_today",
    label: "Bekleyen / No-Show Adayları",
    path: "/no-show-today",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },

  // ──── FINANCE GROUP ────────────────────────────────
  {
    key: "night_audit",
    label: "Gece Denetimi",
    path: "/night-audit",
    moduleKey: "night_audit",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },
  {
    key: "invoices",
    label: "Fatura & Finans",
    path: "/app/invoices",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },
  {
    key: "konaklama_vergisi",
    label: "Konaklama Vergisi",
    path: "/app/konaklama-vergisi",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },
  {
    key: "mevzuat_raporlari",
    label: "Mevzuat Raporları",
    path: "/app/mevzuat-raporlari",
    moduleKey: "basic_reporting",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },
  {
    key: "help_center",
    label: "Yardım Merkezi",
    path: "/app/help",
    tier: "starter",
    group: "starter",
    navGroup: "management",
  },
  {
    key: "academy",
    label: "Akademi",
    path: "/app/academy",
    tier: "addon",
    group: "core",
    navGroup: "management",
    moduleKey: "academy",
  },

  // ──── CHANNELS GROUP — Normal kullanici (otel personeli) ─────────
  {
    key: "cm_dashboard",
    label: "CM Dashboard",
    path: "/cm-dashboard",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    // /cm-dashboard → /channels?tab=dashboard redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "dashboard",
  },
  {
    key: "go_live_readiness",
    label: "Go-Live Hazırlık",
    path: "/go-live-readiness",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "channel_manager",
    label: "Channel Manager",
    path: "/app/channel-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "unified_rate_manager",
    label: "Fiyat & Musaitlik",
    path: "/unified-rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "room_mapping_wizard",
    label: "Oda Eslestirme Sihirbazi",
    path: "/room-mapping-wizard",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "travel_agent_arap",
    label: "Acente AR/AP",
    path: "/travel-agent-arap",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },
  {
    key: "agency_management",
    label: "Acente Yönetimi",
    path: "/agency-management",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },
  {
    key: "incoming_agency_contracts",
    label: "Gelen Acente Talepleri",
    path: "/app/incoming-agency-contracts",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },
  {
    key: "agency_content",
    label: "Icerik Dagitimi",
    path: "/agency-content",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },
  {
    key: "b2b_analytics",
    label: "B2B Analitik",
    path: "/b2b-analytics",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "report_scheduler",
    label: "Rapor Zamanlayıcı",
    path: "/report-scheduler",
    moduleKey: "basic_reporting",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },

  // ──── CHANNELS GROUP — Admin (kanal operasyonlari) ────────────
  {
    key: "channel_ops",
    label: "Operasyon Merkezi",
    path: "/channel-ops",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    // /channel-ops → /channels?tab=ops redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "ops",
  },
  {
    key: "channel_connections",
    label: "Kanal Baglantilari",
    path: "/channel-connections",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    // /channel-connections → /channels?tab=connections redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "connections",
  },
  {
    key: "wire_failures",
    label: "Wire Failure Takibi",
    path: "/wire-failures",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "ari_push",
    label: "ARI Push Engine",
    path: "/ari-push",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "lockdown_dashboard",
    label: "Lockdown Dashboard",
    path: "/lockdown",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },

  // ──── CHANNELS — Hidden (backward compat, unified covers these) ──
  {
    key: "hr_rate_manager",
    label: "HotelRunner - Fiyat ve Musaitlik",
    path: "/hr-rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "rate_manager",
    label: "Exely - Fiyat ve Musaitlik",
    path: "/rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "hotelrunner",
    label: "HotelRunner",
    path: "/hotelrunner",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "exely",
    label: "Exely",
    path: "/exely",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "data_model",
    label: "Data Model",
    path: "/data-model",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "integration_hub",
    label: "Integration Hub",
    path: "/app/integration-hub",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
    hidden: true,
  },
  {
    key: "admin_hub",
    label: "Yönetim Merkezi",
    path: "/app/admin-hub",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "admin_control_panel",
    label: "Yönetim Kontrol Paneli",
    path: "/app/admin-control-panel",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "integrations_overview",
    label: "Entegrasyon Genel Bakış",
    path: "/admin/integrations-overview",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "integration_credentials",
    label: "Entegrasyon Anahtarları",
    path: "/admin/integration-credentials",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "capx_integration",
    label: "CapX Entegrasyonu",
    path: "/admin/capx-integration",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    requireSuperAdmin: true,
  },

  // ──── REPORTS GROUP ────────────────────────────────
  {
    key: "reports_basic",
    label: "Raporlar",
    path: "/app/raporlar",
    moduleKey: "basic_reporting",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    key: "report_builder",
    label: "Rapor Oluşturucu",
    path: "/app/rapor-olusturucu",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },

  // ──── ADVANCED GROUP ───────────────────────────────
  {
    key: "revenue_hub",
    label: "Gelir Merkezi",
    path: "/app/revenue-hub",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "gelir_yonetimi",
    label: "Gelir Yönetimi",
    path: "/app/gelir-yonetimi",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
    hidden: true, // T007: Gelir Merkezi (revenue-hub) içine taşındı
  },
  {
    key: "displacement_analysis",
    label: "Displacement Analizi",
    path: "/displacement-analysis",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
    hidden: true, // T007: Gelir Merkezi (revenue-hub) içine taşındı
  },
  {
    key: "ai_zeka",
    label: "AI & Zeka",
    path: "/app/ai",
    tier: "enterprise",
    group: "advanced",
    moduleKey: "ai",
    navGroup: "advanced",
  },
  {
    key: "mailing",
    label: "E-posta Pazarlama",
    path: "/app/mailing",
    tier: "basic",
    group: "core",
    navGroup: "advanced",
  },
  {
    key: "onboarding_wizard",
    label: "Kurulum Sihirbazı",
    path: "/app/onboarding",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    key: "module_store",
    label: "Modül Pazarı",
    path: "/app/module-store",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    key: "pci_compliance",
    label: "PCI-DSS Uyum",
    path: "/app/compliance/pci",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    key: "webhook_outbox_admin",
    label: "Outbox & Webhook DLQ",
    path: "/admin/webhook-outbox",
    tier: "professional",
    group: "core",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "early_warning_dashboard",
    label: "Erken Uyarı Motoru",
    path: "/admin/early-warning",
    tier: "professional",
    group: "core",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "module_discovery",
    label: "Modül Keşfi",
    path: "/admin/module-discovery",
    tier: "basic",
    group: "core",
    navGroup: "admin",
    requireSuperAdmin: true,
  },
  {
    key: "xchange",
    label: "Xchange (SXI)",
    path: "/app/xchange",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    key: "mice",
    label: "MICE & Banquet",
    path: "/app/mice",
    moduleKey: "mice",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "afsadakat",
    label: "Sadakat & Inbox",
    path: "/app/afsadakat",
    moduleKey: "af_sadakat",
    tier: "basic",
    group: "core",
    navGroup: "management",
  },
  {
    key: "messaging_dashboard",
    label: "Mesajlaşma Merkezi",
    path: "/messaging-dashboard",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "analitik_raporlar",
    label: "Analitik & Raporlar",
    path: "/app/analitik",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },

  // ──── INFRASTRUCTURE GROUP ─────────────────────────
  // Moved from channels: platform-level ops tools
  {
    key: "control_plane",
    label: "Control Plane",
    path: "/control-plane",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "runtime_cockpit",
    label: "Runtime Cockpit",
    path: "/runtime-cockpit",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "incident_panel",
    label: "Incident Panel",
    path: "/incidents",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "system_health",
    label: "System Health",
    path: "/system-health",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "security_hardening",
    label: "Güvenlik & Güçlendirme",
    path: "/security-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "encryption_management",
    label: "Şifreleme Yönetimi",
    path: "/encryption-management",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "production_golive",
    label: "Production Go-Live",
    path: "/production-golive",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },

  // ──── INFRASTRUCTURE — Hidden (deep platform ops, direct URL still works) ──
  {
    key: "data_pipeline",
    label: "Data Pipeline",
    path: "/data-pipeline",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "event_bus",
    label: "Event Bus",
    path: "/event-bus",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "runtime_infrastructure",
    label: "Runtime Infrastructure",
    path: "/runtime-infrastructure",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "platform_scaling",
    label: "Platform Scaling",
    path: "/platform-scaling",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "enterprise_live",
    label: "Enterprise Live",
    path: "/enterprise-live",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },

  // ──── STANDALONE: Settings ─────────────────────────
  {
    key: "settings",
    label: "Ayarlar",
    path: "/app/settings",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── HIDDEN ───────────────────────────────────────
  {
    key: "marketplace",
    label: "Marketplace",
    path: "/app/marketplace",
    moduleKey: "marketplace",
    tier: "enterprise",
    group: "enterprise",
    navGroup: null,
    hidden: true,
  },

  // ──── SUPER ADMIN ONLY ─────────────────────────────
  {
    key: "admin_tenants",
    label: "Otel Yönetimi",
    path: "/admin/tenants",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "admin_vendors",
    label: "Tedarikci Yönetimi",
    path: "/admin/vendors",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "admin_module_report",
    label: "Modul Raporu",
    path: "/admin/module-report",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "admin_leads",
    label: "Leads",
    path: "/app/admin/leads",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "governance",
    label: "Governance",
    path: "/admin/governance",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "site_content",
    label: "Landing İçeriği",
    path: "/admin/site-content",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "quick_id_settings",
    label: "Kimlik Tarama (Quick-ID)",
    path: "/admin/quick-id",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
  {
    key: "room_qr_requests",
    label: "Oda QR Talepleri",
    path: "/app/room-requests",
    group: "operations",
    navGroup: "operations",
    icon: "MessageSquare",
    moduleKey: "room_qr_requests",
    tier: "basic",
  },
  {
    key: "room_qr_codes",
    label: "Oda QR Kodları",
    path: "/admin/room-qr-codes",
    group: "admin",
    navGroup: "admin",
    icon: "QrCode",
    moduleKey: "room_qr_requests",
    tier: "basic",
    requireSuperAdmin: true,
  },
  {
    key: "api_docs",
    label: "API Dokumantasyon",
    path: "/b2b/docs",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
  },
];

// Legacy compatibility
export const PMS_LITE_NAV_KEYS = new Set([
  'dashboard',
  'reservation_calendar',
  'pms',
  'reports_basic',
  'settings',
]);
