// Central navigation configuration for main sidebar/top nav
// Each item maps to a module key from the 3-tier subscription system

// Tier that includes this module by default
// basic = all plans, professional = pro+enterprise, enterprise = enterprise only

// ─── NAV GROUPS for top bar dropdown menus ──────────
export const NAV_GROUPS = [
  {
    id: "operations",
    label: "Operasyon",
    icon: "Hotel",
  },
  {
    id: "reservations",
    label: "Rezervasyon",
    icon: "CalendarCheck",
  },
  {
    id: "finance",
    label: "Finans",
    icon: "DollarSign",
  },
  {
    id: "channels",
    label: "Kanallar",
    icon: "Layers",
  },
  {
    id: "reports",
    label: "Raporlar",
    icon: "BarChart3",
  },
  {
    id: "advanced",
    label: "Gelismis",
    icon: "Zap",
  },
  {
    id: "infrastructure",
    label: "Altyapi",
    icon: "Server",
  },
];

export const NAV_ITEMS = [
  // ──── STANDALONE (shown as direct buttons) ─────────
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/app/dashboard",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── OPERATIONS GROUP ─────────────────────────────
  {
    key: "reservation_calendar",
    label: "Takvim",
    path: "/app/reservation-calendar",
    moduleKey: "reservation_calendar",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "pms",
    label: "PMS",
    path: "/app/pms",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "pms_operations",
    label: "PMS Operasyonlar",
    path: "/pms-operations",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "folio_detail",
    label: "Folio Detail",
    path: "/folio-detail",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
    hidden: true,
  },
  {
    key: "housekeeping_status",
    label: "Housekeeping",
    path: "/housekeeping-status",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "wake_up_calls",
    label: "Uyandirma Cagrisi",
    path: "/wake-up-calls",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "lost_found",
    label: "Kayip Esya",
    path: "/lost-found",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
  },
  {
    key: "guest_journey",
    label: "Guest Journey",
    path: "/guest-journey",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "operations",
  },
  {
    key: "operational_events",
    label: "Olay Merkezi",
    path: "/operational-events",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "operations",
  },

  // ──── RESERVATIONS GROUP ───────────────────────────
  {
    key: "group_bookings",
    label: "Grup Rezervasyonlari",
    path: "/group-bookings-manage",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "deposit_tracking",
    label: "Depozito Takibi",
    path: "/deposit-tracking",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "group_folio",
    label: "Grup Folio",
    path: "/group-folio",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },
  {
    key: "no_show_analytics",
    label: "No-Show Analitik",
    path: "/no-show-analytics",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reservations",
  },

  // ──── FINANCE GROUP ────────────────────────────────
  {
    key: "night_audit",
    label: "Gece Denetimi",
    path: "/night-audit",
    moduleKey: "night_audit",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },
  {
    key: "invoices",
    label: "Fatura & Finans",
    path: "/app/invoices",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },
  {
    key: "cost_management",
    label: "Maliyet",
    path: "/app/cost-management",
    moduleKey: "cost_management",
    tier: "professional",
    group: "professional",
    navGroup: "finance",
  },

  // ──── CHANNELS GROUP — Normal kullanici (otel personeli) ─────────
  {
    key: "channel_manager",
    label: "Channel Manager",
    path: "/app/channel-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "hr_rate_manager",
    label: "HotelRunner - Fiyat ve Musaitlik",
    path: "/hr-rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "rate_manager",
    label: "Exely - Fiyat ve Musaitlik",
    path: "/rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "room_mapping_wizard",
    label: "Oda Eslestirme Sihirbazi",
    path: "/room-mapping-wizard",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
  },
  {
    key: "agency_management",
    label: "Acente Yonetimi",
    path: "/agency-management",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },
  {
    key: "agency_content",
    label: "Icerik Dagitimi",
    path: "/agency-content",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "channels",
  },

  // ──── CHANNELS GROUP — Sadece Admin (teknik yonetim) ───────────
  {
    key: "channel_connections",
    label: "Kanal Baglantilari",
    path: "/channel-connections",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "hotelrunner",
    label: "HotelRunner",
    path: "/hotelrunner",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "exely",
    label: "Exely",
    path: "/exely",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "wire_failures",
    label: "Wire Failure Takibi",
    path: "/wire-failures",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "ari_push",
    label: "ARI Push Engine",
    path: "/ari-push",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "lockdown_dashboard",
    label: "Lockdown Dashboard",
    path: "/lockdown",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "incident_panel",
    label: "Incident Panel",
    path: "/incidents",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "runtime_cockpit",
    label: "Runtime Cockpit",
    path: "/runtime-cockpit",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "control_plane",
    label: "Control Plane",
    path: "/control-plane",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "data_model",
    label: "Data Model",
    path: "/data-model",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "integration_hub",
    label: "Integration Hub",
    path: "/app/integration-hub",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },
  {
    key: "admin_control_panel",
    label: "Admin Control Panel",
    path: "/app/admin-control-panel",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "channels",
    requireSuperAdmin: true,
  },

  // ──── REPORTS GROUP ────────────────────────────────
  {
    key: "reports_basic",
    label: "Raporlar",
    path: "/app/raporlar",
    moduleKey: "basic_reporting",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    key: "reports",
    label: "Gelismis Raporlar",
    path: "/app/gelismis-raporlar",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },
  {
    key: "report_builder",
    label: "Rapor Olusturucu",
    path: "/app/rapor-olusturucu",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },

  // ──── ADVANCED GROUP ───────────────────────────────
  {
    key: "rms",
    label: "Revenue (RMS)",
    path: "/app/rms",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "ai",
    label: "AI Modulleri",
    path: "/app/ai",
    moduleKey: "ai",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "revenue_engine",
    label: "Revenue Engine",
    path: "/revenue-engine",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "data_intelligence",
    label: "Data Intelligence",
    path: "/data-intelligence",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "messaging_dashboard",
    label: "Messaging Center",
    path: "/messaging-dashboard",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "ml_scheduler",
    label: "ML Scheduler",
    path: "/ml-scheduler",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "revenue_autopilot_v2",
    label: "Revenue Autopilot",
    path: "/revenue-autopilot-v2",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },
  {
    key: "analytics_export",
    label: "Analytics Export",
    path: "/analytics-export",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "advanced",
  },

  // ──── INFRASTRUCTURE GROUP ─────────────────────────
  {
    key: "data_pipeline",
    label: "Data Pipeline",
    path: "/data-pipeline",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "event_bus",
    label: "Event Bus",
    path: "/event-bus",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "system_health",
    label: "System Health",
    path: "/system-health",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "observability",
    label: "Observability",
    path: "/observability",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "security_hardening",
    label: "Security Hardening",
    path: "/security-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "runtime_infrastructure",
    label: "Runtime Infrastructure",
    path: "/runtime-infrastructure",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "infra_hardening",
    label: "Infrastructure Hardening",
    path: "/infra-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "pii_strict_mode",
    label: "PII Strict Mode",
    path: "/pii-strict-mode",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "production_golive",
    label: "Production Go-Live",
    path: "/production-golive",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "platform_scaling",
    label: "Platform Scaling",
    path: "/platform-scaling",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "enterprise_live",
    label: "Enterprise Live",
    path: "/enterprise-live",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },

  // ──── STANDALONE: Settings ─────────────────────────
  {
    key: "settings",
    label: "Ayarlar",
    path: "/app/settings",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── HIDDEN ───────────────────────────────────────
  {
    key: "marketplace",
    label: "Marketplace",
    path: "/app/marketplace",
    moduleKey: "marketplace",
    tier: "enterprise",
    group: "enterprise",
    navGroup: null,
    hidden: true,
  },

  // ──── SUPER ADMIN ONLY ─────────────────────────────
  {
    key: "admin_tenants",
    label: "Otel Yonetimi",
    path: "/admin/tenants",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: null,
  },
  {
    key: "admin_module_report",
    label: "Modul Raporu",
    path: "/admin/module-report",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: null,
  },
  {
    key: "admin_leads",
    label: "Leads",
    path: "/app/admin/leads",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: null,
  },
  {
    key: "governance",
    label: "Governance",
    path: "/admin/governance",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: null,
  },
];

// Legacy compatibility
export const PMS_LITE_NAV_KEYS = new Set([
  'dashboard',
  'reservation_calendar',
  'pms',
  'reports_basic',
  'settings',
]);
