// Central navigation configuration for main sidebar/top nav
// Each item maps to a module key from the 3-tier subscription system
// Module keys: pms, reservation_calendar, dashboard, guests, housekeeping, basic_reporting,
//   settings, pms_mobile, invoices_basic, channel_manager, folio_management, night_audit,
//   invoices, cost_management, reports, mobile_housekeeping, rate_management, booking_engine,
//   guest_advanced, revenue_management, multi_property, group_sales, sales_crm, loyalty_program,
//   gm_dashboards, mobile_revenue, advanced_analytics, api_access, white_label, audit_trail,
//   ai, ai_chatbot, ai_pricing, ai_whatsapp, ai_predictive, ai_reputation, ai_revenue_autopilot, ai_social_radar

// Tier that includes this module by default
// basic = all plans, professional = pro+enterprise, enterprise = enterprise only
export const NAV_ITEMS = [
  // ──── CORE (Basic plan) ────────────────────────────
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/app/dashboard",
    moduleKey: "dashboard",
    tier: "basic",
    group: "core",
  },
  {
    key: "reservation_calendar",
    label: "Takvim",
    path: "/app/reservation-calendar",
    moduleKey: "reservation_calendar",
    tier: "basic",
    group: "core",
  },
  {
    key: "pms",
    label: "PMS",
    path: "/app/pms",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
  },
  {
    key: "pms_operations",
    label: "PMS Operasyonlar",
    path: "/pms-operations",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
  },
  {
    key: "folio_detail",
    label: "Folio Detail",
    path: "/folio-detail",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
  },
  {
    key: "revenue_engine",
    label: "Revenue Engine",
    path: "/revenue-engine",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "operational_events",
    label: "Olay Merkezi",
    path: "/operational-events",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
  },
  {
    key: "guest_journey",
    label: "Guest Journey",
    path: "/guest-journey",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
  },
  {
    key: "platform_scaling",
    label: "Platform Scaling",
    path: "/platform-scaling",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "enterprise_live",
    label: "Enterprise Live",
    path: "/enterprise-live",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "reports_basic",
    label: "Raporlar",
    path: "/app/raporlar",
    moduleKey: "basic_reporting",
    tier: "basic",
    group: "core",
  },
  {
    key: "settings",
    label: "Ayarlar",
    path: "/app/settings",
    moduleKey: "settings",
    tier: "basic",
    group: "core",
  },

  // ──── PROFESSIONAL ─────────────────────────────────
  {
    key: "invoices",
    label: "Fatura & Finans",
    path: "/app/invoices",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
  },
  {
    key: "cost_management",
    label: "Maliyet",
    path: "/app/cost-management",
    moduleKey: "cost_management",
    tier: "professional",
    group: "professional",
  },
  {
    key: "channel_manager",
    label: "Channel Manager",
    path: "/app/channel-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
  },
  {
    key: "integration_hub",
    label: "Integration Hub",
    path: "/app/integration-hub",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
  },
  {
    key: "admin_control_panel",
    label: "Admin Control Panel",
    path: "/app/admin-control-panel",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
  },
  {
    key: "reports",
    label: "Gelişmiş Raporlar",
    path: "/app/gelismis-raporlar",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
  },
  {
    key: "report_builder",
    label: "Rapor Oluşturucu",
    path: "/app/rapor-olusturucu",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
  },

  // ──── ENTERPRISE ───────────────────────────────────
  {
    key: "rms",
    label: "Revenue (RMS)",
    path: "/app/rms",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "ai",
    label: "AI Modülleri",
    path: "/app/ai",
    moduleKey: "ai",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "data_intelligence",
    label: "Data Intelligence",
    path: "/data-intelligence",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "messaging_dashboard",
    label: "Messaging Center",
    path: "/messaging-dashboard",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "ml_scheduler",
    label: "ML Scheduler",
    path: "/ml-scheduler",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "revenue_autopilot_v2",
    label: "Revenue Autopilot",
    path: "/revenue-autopilot-v2",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "analytics_export",
    label: "Analytics Export",
    path: "/analytics-export",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "data_pipeline",
    label: "Data Pipeline",
    path: "/data-pipeline",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "event_bus",
    label: "Event Bus",
    path: "/event-bus",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "system_health",
    label: "System Health",
    path: "/system-health",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "observability",
    label: "Observability",
    path: "/observability",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "security_hardening",
    label: "Security Hardening",
    path: "/security-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "runtime_infrastructure",
    label: "Runtime Infrastructure",
    path: "/runtime-infrastructure",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "infra_hardening",
    label: "Infrastructure Hardening",
    path: "/infra-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "production_golive",
    label: "Production Go-Live",
    path: "/production-golive",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
  },
  {
    key: "marketplace",
    label: "Marketplace",
    path: "/app/marketplace",
    moduleKey: "marketplace",
    tier: "enterprise",
    group: "enterprise",
    hidden: true,
  },

  // ──── SUPER ADMIN ONLY ─────────────────────────────
  {
    key: "admin_tenants",
    label: "Otel Yönetimi",
    path: "/admin/tenants",
    requireSuperAdmin: true,
    group: "admin",
  },
  {
    key: "admin_module_report",
    label: "Modül Raporu",
    path: "/admin/module-report",
    requireSuperAdmin: true,
    group: "admin",
  },
  {
    key: "admin_leads",
    label: "Leads",
    path: "/app/admin/leads",
    requireSuperAdmin: true,
    group: "admin",
  },
];

// Legacy compatibility
export const PMS_LITE_NAV_KEYS = new Set([
  'dashboard',
  'reservation_calendar',
  'pms',
  'reports_basic',
  'settings',
]);
