export const permissionLabels = {
  view_bookings: 'Rezervasyonları görüntüle',
  create_booking: 'Rezervasyon oluştur',
  edit_booking: 'Rezervasyon düzenle',
  checkin: 'Giriş yap',
  checkout: 'Çıkış yap',
  view_folio: 'Folyo ve kasa görüntüle',
  post_charge: 'Ücret ekle',
  post_payment: 'Ödeme al',
  view_companies: 'Şirketleri görüntüle',
  view_hk_board: 'Kat hizmetleri panosunu görüntüle',
  update_room_status: 'Oda durumunu güncelle',
  assign_task: 'Görev ata',
  view_reports: 'Operasyon raporlarını görüntüle',
  view_financial_reports: 'Finansal raporları görüntüle',
  run_night_audit: 'Gece denetimi / gün sonu çalıştır',
  view_hr: 'İnsan kaynaklarını görüntüle',
  view_procurement: 'Satınalmayı görüntüle',
  view_contact_center: 'İletişim merkezini görüntüle',
  manage_contact_center: 'İletişim merkezi işlemlerini yönet',
  send_urgent_message: 'Acil mesaj gönder',
};
