"""
Property Type Profiling System
Adapts Syroce PMS for any accommodation type — from 1-room pensions to 1000-room resorts.
Each profile defines which modules are relevant, recommended settings, and UI behavior.
"""

from enum import Enum


class PropertyType(str, Enum):
    PENSION = "pension"
    VILLA = "villa"
    HOSTEL = "hostel"
    MOTEL = "motel"
    APART_HOTEL = "apart_hotel"
    BOUTIQUE_HOTEL = "boutique_hotel"
    CAMPING = "camping"
    CITY_HOTEL = "city_hotel"
    BUSINESS_HOTEL = "business_hotel"
    RESORT_SUMMER = "resort_summer"
    RESORT_WINTER = "resort_winter"
    RESORT_THERMAL = "resort_thermal"
    HOTEL_3STAR = "hotel_3star"
    HOTEL_4STAR = "hotel_4star"
    HOTEL_5STAR = "hotel_5star"


class DashboardLayout(str, Enum):
    SIMPLE = "simple"
    STANDARD = "standard"
    ADVANCED = "advanced"
    FULL = "full"


PROPERTY_PROFILES: dict[str, dict] = {
    PropertyType.PENSION: {
        "name_en": "Pension / Guesthouse",
        "name_tr": "Pansiyon",
        "icon": "Home",
        "description_en": "Small family-run accommodation with basic needs. Quick reservations, simple management.",
        "description_tr": "Küçük aile işletmesi konaklama. Hızlı rezervasyon, kolay yönetim.",
        "room_range": {"min": 1, "max": 15},
        "recommended_tier": "mini",
        "dashboard_layout": DashboardLayout.SIMPLE,
        "typical_staff": 2,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": False,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": False,
            "folio_management": False,
            "night_audit": False,
            "invoices": False,
            "cost_management": False,
            "reports": False,
            "mobile_housekeeping": False,
            "rate_management": False,
            "booking_engine": False,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure", "channels"],
        "hidden_nav_items": [
            "housekeeping_status",
            "wake_up_calls",
            "lost_found",
            "guest_journey",
            "operational_events",
            "service_recovery",
            "group_bookings",
            "deposit_tracking",
            "group_folio",
            "no_show_analytics",
            "night_audit",
            "invoices",
            "cost_management",
            "displacement_analysis",
            "messaging_dashboard",
            "report_builder",
        ],
        "special_settings": {
            "simplified_checkin": True,
            "quick_reservation_mode": True,
            "auto_room_assign": True,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": False,
        },
    },
    PropertyType.VILLA: {
        "name_en": "Villa / Holiday Home",
        "name_tr": "Villa / Tatil Evi",
        "icon": "TreePalm",
        "description_en": "Individual holiday rental properties. Calendar-focused, minimal operations.",
        "description_tr": "Bireysel tatil kiralama mülkleri. Takvim odaklı, minimal operasyon.",
        "room_range": {"min": 1, "max": 10},
        "recommended_tier": "mini",
        "dashboard_layout": DashboardLayout.SIMPLE,
        "typical_staff": 1,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": False,
            "folio_management": False,
            "night_audit": False,
            "invoices": False,
            "cost_management": False,
            "reports": False,
            "mobile_housekeeping": False,
            "rate_management": False,
            "booking_engine": False,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure", "channels"],
        "hidden_nav_items": [
            "wake_up_calls",
            "lost_found",
            "guest_journey",
            "operational_events",
            "service_recovery",
            "group_bookings",
            "deposit_tracking",
            "group_folio",
            "no_show_analytics",
            "night_audit",
            "invoices",
            "cost_management",
            "displacement_analysis",
            "messaging_dashboard",
            "report_builder",
        ],
        "special_settings": {
            "simplified_checkin": True,
            "quick_reservation_mode": True,
            "auto_room_assign": True,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": False,
            "calendar_primary_view": True,
        },
    },
    PropertyType.HOSTEL: {
        "name_en": "Hostel / Backpacker",
        "name_tr": "Hostel",
        "icon": "Bed",
        "description_en": "Budget accommodation with shared rooms. Bed-level management, group-friendly.",
        "description_tr": "Ortak odalı bütçe konaklama. Yatak bazlı yönetim, grup dostu.",
        "room_range": {"min": 5, "max": 50},
        "recommended_tier": "basic",
        "dashboard_layout": DashboardLayout.STANDARD,
        "typical_staff": 3,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": False,
            "folio_management": False,
            "night_audit": False,
            "invoices": False,
            "cost_management": False,
            "reports": False,
            "mobile_housekeeping": False,
            "rate_management": False,
            "booking_engine": False,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure"],
        "hidden_nav_items": [
            "guest_journey",
            "operational_events",
            "group_bookings",
            "deposit_tracking",
            "group_folio",
            "displacement_analysis",
            "messaging_dashboard",
            "report_builder",
        ],
        "special_settings": {
            "simplified_checkin": True,
            "quick_reservation_mode": True,
            "auto_room_assign": False,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
            "bed_level_management": True,
        },
    },
    PropertyType.MOTEL: {
        "name_en": "Motel / Roadside Inn",
        "name_tr": "Motel",
        "icon": "Car",
        "description_en": "Roadside short-stay accommodation. Fast check-in/out, hourly pricing option.",
        "description_tr": "Yol kenarı kısa konaklamalı tesis. Hızlı giriş/çıkış, saatlik fiyat seçeneği.",
        "room_range": {"min": 10, "max": 50},
        "recommended_tier": "basic",
        "dashboard_layout": DashboardLayout.STANDARD,
        "typical_staff": 3,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": False,
            "folio_management": False,
            "night_audit": False,
            "invoices": False,
            "cost_management": False,
            "reports": False,
            "mobile_housekeeping": False,
            "rate_management": False,
            "booking_engine": False,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure"],
        "hidden_nav_items": [
            "guest_journey",
            "operational_events",
            "group_bookings",
            "deposit_tracking",
            "group_folio",
            "displacement_analysis",
            "messaging_dashboard",
            "report_builder",
        ],
        "special_settings": {
            "simplified_checkin": True,
            "quick_reservation_mode": True,
            "auto_room_assign": True,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
            "hourly_pricing": True,
        },
    },
    PropertyType.APART_HOTEL: {
        "name_en": "Apart Hotel / Serviced Apartments",
        "name_tr": "Apart Otel",
        "icon": "Building",
        "description_en": "Extended-stay apartments with hotel services. Long-term billing, periodic housekeeping.",
        "description_tr": "Otel hizmetli uzun süreli daireler. Uzun dönem faturalandırma, periyodik temizlik.",
        "room_range": {"min": 5, "max": 100},
        "recommended_tier": "professional",
        "dashboard_layout": DashboardLayout.STANDARD,
        "typical_staff": 5,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure"],
        "hidden_nav_items": [
            "wake_up_calls",
            "guest_journey",
            "operational_events",
            "group_bookings",
            "group_folio",
            "displacement_analysis",
            "messaging_dashboard",
        ],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
            "long_stay_billing": True,
            "weekly_housekeeping": True,
        },
    },
    PropertyType.BOUTIQUE_HOTEL: {
        "name_en": "Boutique Hotel",
        "name_tr": "Butik Otel",
        "icon": "Gem",
        "description_en": "Unique character hotel with personalized guest experience. Upsell, concierge, guest journey.",
        "description_tr": "Kişiselleştirilmiş misafir deneyimi sunan özgün karakter otel. Upsell, concierge, misafir yolculuğu.",
        "room_range": {"min": 5, "max": 50},
        "recommended_tier": "professional",
        "dashboard_layout": DashboardLayout.STANDARD,
        "typical_staff": 8,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["infrastructure"],
        "hidden_nav_items": [
            "group_bookings",
            "group_folio",
            "displacement_analysis",
        ],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
            "personalized_welcome": True,
        },
    },
    PropertyType.CAMPING: {
        "name_en": "Camping / Glamping",
        "name_tr": "Kamp Alanı / Glamping",
        "icon": "Tent",
        "description_en": "Outdoor accommodation with pitch/unit management. Seasonal operations.",
        "description_tr": "Pitch/ünite yönetimli açık hava konaklama. Sezonluk operasyon.",
        "room_range": {"min": 5, "max": 100},
        "recommended_tier": "basic",
        "dashboard_layout": DashboardLayout.SIMPLE,
        "typical_staff": 3,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": False,
            "folio_management": False,
            "night_audit": False,
            "invoices": False,
            "cost_management": False,
            "reports": False,
            "mobile_housekeeping": False,
            "rate_management": False,
            "booking_engine": False,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["advanced", "infrastructure", "channels"],
        "hidden_nav_items": [
            "wake_up_calls",
            "lost_found",
            "guest_journey",
            "operational_events",
            "service_recovery",
            "group_bookings",
            "deposit_tracking",
            "group_folio",
            "no_show_analytics",
            "night_audit",
            "invoices",
            "cost_management",
            "displacement_analysis",
            "messaging_dashboard",
            "report_builder",
        ],
        "special_settings": {
            "simplified_checkin": True,
            "quick_reservation_mode": True,
            "auto_room_assign": False,
            "show_upsell": False,
            "show_minibar": False,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
            "seasonal_operation": True,
        },
    },
    PropertyType.CITY_HOTEL: {
        "name_en": "City Hotel",
        "name_tr": "Şehir Oteli",
        "icon": "Building2",
        "description_en": "Urban hotel for business and leisure travelers. Channel management, night audit, full operations.",
        "description_tr": "İş ve tatil amaçlı şehir oteli. Kanal yönetimi, gece denetimi, tam operasyon.",
        "room_range": {"min": 20, "max": 200},
        "recommended_tier": "professional",
        "dashboard_layout": DashboardLayout.ADVANCED,
        "typical_staff": 15,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["infrastructure"],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
        },
    },
    PropertyType.BUSINESS_HOTEL: {
        "name_en": "Business / Conference Hotel",
        "name_tr": "İş / Kongre Oteli",
        "icon": "Briefcase",
        "description_en": "Corporate-focused hotel with meeting rooms and MICE. Group bookings, corporate billing.",
        "description_tr": "Toplantı salonu ve MICE odaklı kurumsal otel. Grup rezervasyonları, kurumsal faturalandırma.",
        "room_range": {"min": 50, "max": 500},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.ADVANCED,
        "typical_staff": 30,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": False,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": False,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": False,
            "ai_predictive": True,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": False,
            "show_mice": True,
            "show_loyalty": True,
            "show_kbs_police": True,
            "corporate_billing": True,
            "meeting_room_booking": True,
        },
    },
    PropertyType.RESORT_SUMMER: {
        "name_en": "Summer / Beach Resort",
        "name_tr": "Yaz / Sahil Oteli",
        "icon": "Sun",
        "description_en": "Seasonal beach resort with all-inclusive options. Spa, activities, animation, F&B focus.",
        "description_tr": "Her şey dahil seçenekli sezonluk sahil oteli. Spa, aktiviteler, animasyon, yiyecek-içecek odaklı.",
        "room_range": {"min": 50, "max": 1000},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.FULL,
        "typical_staff": 50,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": False,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": False,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": True,
            "ai_predictive": True,
            "ai_reputation": True,
            "ai_revenue_autopilot": True,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": True,
            "show_mice": True,
            "show_loyalty": True,
            "show_kbs_police": True,
            "all_inclusive": True,
            "seasonal_operation": True,
            "animation_schedule": True,
            "beach_management": True,
        },
    },
    PropertyType.RESORT_WINTER: {
        "name_en": "Winter / Ski Resort",
        "name_tr": "Kış / Kayak Oteli",
        "icon": "Snowflake",
        "description_en": "Winter sports resort with ski pass integration. Seasonal, spa, equipment rental.",
        "description_tr": "Ski pass entegrasyonlu kış sporları oteli. Sezonluk, spa, ekipman kiralama.",
        "room_range": {"min": 30, "max": 500},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.FULL,
        "typical_staff": 40,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": False,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": False,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": True,
            "ai_predictive": True,
            "ai_reputation": True,
            "ai_revenue_autopilot": True,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": True,
            "show_mice": False,
            "show_loyalty": True,
            "show_kbs_police": True,
            "seasonal_operation": True,
            "equipment_rental": True,
            "ski_pass_integration": True,
        },
    },
    PropertyType.RESORT_THERMAL: {
        "name_en": "Thermal / Wellness Resort",
        "name_tr": "Termal / Sağlık Oteli",
        "icon": "Droplets",
        "description_en": "Health and wellness resort with spa focus. Treatment scheduling, medical tourism.",
        "description_tr": "Spa odaklı sağlık ve wellness oteli. Tedavi planlama, sağlık turizmi.",
        "room_range": {"min": 30, "max": 300},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.ADVANCED,
        "typical_staff": 35,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": False,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": False,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": True,
            "ai_predictive": True,
            "ai_reputation": True,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": True,
            "show_mice": False,
            "show_loyalty": True,
            "show_kbs_police": True,
            "treatment_scheduling": True,
            "medical_tourism": True,
        },
    },
    PropertyType.HOTEL_3STAR: {
        "name_en": "3-Star Hotel",
        "name_tr": "3 Yıldızlı Otel",
        "icon": "Star",
        "description_en": "Standard comfort hotel. Essential operations with channel management.",
        "description_tr": "Standart konfor oteli. Kanal yönetimli temel operasyonlar.",
        "room_range": {"min": 20, "max": 100},
        "recommended_tier": "professional",
        "dashboard_layout": DashboardLayout.STANDARD,
        "typical_staff": 10,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": False,
            "revenue_management": False,
            "multi_property": False,
            "group_sales": False,
            "sales_crm": False,
            "loyalty_program": False,
            "gm_dashboards": False,
            "mobile_revenue": False,
            "advanced_analytics": False,
            "api_access": False,
            "white_label": False,
            "audit_trail": False,
            "ai": False,
            "ai_chatbot": False,
            "ai_pricing": False,
            "ai_whatsapp": False,
            "ai_predictive": False,
            "ai_reputation": False,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": ["infrastructure"],
        "hidden_nav_items": [
            "displacement_analysis",
            "messaging_dashboard",
        ],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": False,
            "show_spa": False,
            "show_mice": False,
            "show_loyalty": False,
            "show_kbs_police": True,
        },
    },
    PropertyType.HOTEL_4STAR: {
        "name_en": "4-Star Hotel",
        "name_tr": "4 Yıldızlı Otel",
        "icon": "Star",
        "description_en": "Superior hotel with full operations. Guest journey, concierge, upsell, advanced reporting.",
        "description_tr": "Tam operasyonlu üstün otel. Misafir yolculuğu, concierge, upsell, gelişmiş raporlama.",
        "room_range": {"min": 50, "max": 300},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.ADVANCED,
        "typical_staff": 25,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": False,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": False,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": False,
            "ai_predictive": True,
            "ai_reputation": True,
            "ai_revenue_autopilot": False,
            "ai_social_radar": False,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": True,
            "show_mice": True,
            "show_loyalty": True,
            "show_kbs_police": True,
        },
    },
    PropertyType.HOTEL_5STAR: {
        "name_en": "5-Star / Luxury Hotel",
        "name_tr": "5 Yıldızlı / Lüks Otel",
        "icon": "Crown",
        "description_en": "Premium luxury hotel with all features enabled. Full AI, revenue management, MICE, spa, loyalty.",
        "description_tr": "Tüm özelliklerin açık olduğu premium lüks otel. Tam AI, gelir yönetimi, MICE, spa, sadakat.",
        "room_range": {"min": 100, "max": 1000},
        "recommended_tier": "enterprise",
        "dashboard_layout": DashboardLayout.FULL,
        "typical_staff": 80,
        "modules": {
            "pms": True,
            "reservation_calendar": True,
            "dashboard": True,
            "guests": True,
            "housekeeping": True,
            "basic_reporting": True,
            "settings": True,
            "pms_mobile": True,
            "invoices_basic": True,
            "channel_manager": True,
            "folio_management": True,
            "night_audit": True,
            "invoices": True,
            "cost_management": True,
            "reports": True,
            "mobile_housekeeping": True,
            "rate_management": True,
            "booking_engine": True,
            "guest_advanced": True,
            "revenue_management": True,
            "multi_property": True,
            "group_sales": True,
            "sales_crm": True,
            "loyalty_program": True,
            "gm_dashboards": True,
            "mobile_revenue": True,
            "advanced_analytics": True,
            "api_access": True,
            "white_label": True,
            "audit_trail": True,
            "ai": True,
            "ai_chatbot": True,
            "ai_pricing": True,
            "ai_whatsapp": True,
            "ai_predictive": True,
            "ai_reputation": True,
            "ai_revenue_autopilot": True,
            "ai_social_radar": True,
        },
        "hidden_nav_groups": [],
        "hidden_nav_items": [],
        "special_settings": {
            "simplified_checkin": False,
            "quick_reservation_mode": False,
            "auto_room_assign": False,
            "show_upsell": True,
            "show_minibar": True,
            "show_concierge": True,
            "show_spa": True,
            "show_mice": True,
            "show_loyalty": True,
            "show_kbs_police": True,
            "vip_management": True,
            "butler_service": True,
        },
    },
}


def get_property_profile(property_type: str) -> dict | None:
    return PROPERTY_PROFILES.get(property_type)


def get_all_property_types() -> list[dict]:
    result = []
    for key, profile in PROPERTY_PROFILES.items():
        result.append(
            {
                "key": key if isinstance(key, str) else key.value,
                "name_en": profile["name_en"],
                "name_tr": profile["name_tr"],
                "icon": profile["icon"],
                "description_en": profile["description_en"],
                "description_tr": profile["description_tr"],
                "room_range": profile["room_range"],
                "recommended_tier": profile["recommended_tier"],
                "dashboard_layout": profile["dashboard_layout"],
                "typical_staff": profile["typical_staff"],
            }
        )
    return result


def get_modules_for_property_type(property_type: str, subscription_tier: str = None) -> dict[str, bool]:
    profile = get_property_profile(property_type)
    if not profile:
        from domains.admin.subscription_models import get_plan_default_modules

        return get_plan_default_modules(subscription_tier or "basic")

    base_modules = profile["modules"].copy()

    if subscription_tier:
        from domains.admin.subscription_models import get_plan_default_modules

        tier_modules = get_plan_default_modules(subscription_tier)
        for key, tier_enabled in tier_modules.items():
            if not tier_enabled:
                base_modules[key] = False
            elif tier_enabled and key in base_modules:
                base_modules[key] = True

    return base_modules


def get_property_special_settings(property_type: str) -> dict:
    profile = get_property_profile(property_type)
    if not profile:
        return {}
    return profile.get("special_settings", {})


def get_hidden_nav_config(property_type: str) -> dict:
    profile = get_property_profile(property_type)
    if not profile:
        return {"hidden_nav_groups": [], "hidden_nav_items": []}
    return {
        "hidden_nav_groups": profile.get("hidden_nav_groups", []),
        "hidden_nav_items": profile.get("hidden_nav_items", []),
    }
