import { useState, useEffect } from 'react';
import { BookOpen, Key, Search, Hotel, Calendar, DollarSign, FileText, Bell, ChevronRight, Globe, Copy, Check, ArrowLeft, Code, Shield, Zap } from 'lucide-react';

const API_BASE = window.location.origin + '/api/b2b';

const translations = {
  en: {
    title: 'Syroce B2B API',
    subtitle: 'Integration documentation for agency automation systems',
    nav: {
      overview: 'Overview',
      auth: 'Authentication',
      content: 'Content',
      availability: 'Availability',
      rates: 'Rates',
      reservations: 'Reservations',
      webhooks: 'Webhooks',
    },
    overview: {
      heading: 'Getting Started',
      desc: 'The Syroce B2B API allows travel agencies to integrate directly with hotel PMS systems. Query real-time availability, fetch rates, create reservations, and receive webhook notifications — all through a single, unified API.',
      baseUrl: 'Base URL',
      features: 'Key Features',
      featureList: [
        'Real-time room availability checks',
        'Agency-specific and base rate queries',
        'Direct reservation creation with auto PMS sync',
        'Reservation management (list, detail, cancel)',
        'Webhook notifications for status changes',
      ],
      responseFormat: 'Response Format',
      responseDesc: 'All responses are returned in JSON format. Successful responses include relevant data fields. Error responses include a detail message.',
    },
    auth: {
      heading: 'Authentication',
      desc: 'All B2B API endpoints require an API key. Include your key in the request header:',
      headerName: 'Header Name',
      headerValue: 'Header Value',
      obtaining: 'Obtaining an API Key',
      obtainingDesc: 'API keys are issued by the hotel administrator through the Agency Management panel. Contact your hotel partner to request access.',
      security: 'Security Notes',
      securityList: [
        'Keys are SHA-256 hashed on the server — never stored in plaintext',
        'Each key is scoped to a single agency and hotel tenant',
        'Keys can be revoked or regenerated by the hotel at any time',
        'Usage is tracked (request count, last used timestamp)',
      ],
      errors: 'Authentication Errors',
    },
    content: {
      heading: 'Content API',
      desc: 'Retrieve hotel content including room types, services, and general property information. Content must be published to your agency by the hotel.',
      endpoint: 'Endpoint',
      params: 'Parameters',
      noParams: 'No query parameters required.',
      response: 'Response',
      published: 'When content is published',
      notPublished: 'When content is not published',
    },
    availability: {
      heading: 'Availability API',
      desc: 'Check real-time room availability for specified dates. Returns available room count by type with capacity and pricing details.',
      endpoint: 'Endpoint',
      params: 'Query Parameters',
      paramList: [
        { name: 'check_in', type: 'string', required: true, desc: 'Check-in date (YYYY-MM-DD)' },
        { name: 'check_out', type: 'string', required: true, desc: 'Check-out date (YYYY-MM-DD)' },
        { name: 'room_type', type: 'string', required: false, desc: 'Filter by room type (optional)' },
      ],
      response: 'Response',
    },
    rates: {
      heading: 'Rates API',
      desc: 'Fetch rates for specified date range. Returns agency-specific rates if configured, otherwise falls back to base hotel rates.',
      endpoint: 'Endpoint',
      params: 'Query Parameters',
      paramList: [
        { name: 'start_date', type: 'string', required: true, desc: 'Start date (YYYY-MM-DD)' },
        { name: 'end_date', type: 'string', required: true, desc: 'End date (YYYY-MM-DD)' },
        { name: 'room_type', type: 'string', required: false, desc: 'Filter by room type (optional)' },
      ],
      response: 'Response',
    },
    reservations: {
      heading: 'Reservations API',
      desc: 'Create, list, view and cancel reservations. All reservations are automatically synced with the hotel PMS.',
      createTitle: 'Create Reservation',
      createDesc: 'Creates a new reservation and auto-assigns an available room.',
      bodyParams: 'Request Body',
      createParams: [
        { name: 'room_type', type: 'string', required: true, desc: 'Room type name' },
        { name: 'check_in', type: 'string', required: true, desc: 'Check-in date (YYYY-MM-DD)' },
        { name: 'check_out', type: 'string', required: true, desc: 'Check-out date (YYYY-MM-DD)' },
        { name: 'guest_name', type: 'string', required: true, desc: 'Full guest name' },
        { name: 'guest_email', type: 'string', required: false, desc: 'Guest email address' },
        { name: 'guest_phone', type: 'string', required: false, desc: 'Guest phone number' },
        { name: 'adults', type: 'integer', required: false, desc: 'Number of adults (default: 2)' },
        { name: 'children', type: 'integer', required: false, desc: 'Number of children (default: 0)' },
        { name: 'special_requests', type: 'string', required: false, desc: 'Special requests' },
        { name: 'total_amount', type: 'number', required: false, desc: 'Total price (0 = auto-calculate)' },
      ],
      listTitle: 'List Reservations',
      listDesc: 'Retrieve your agency reservations with optional filters.',
      listParams: [
        { name: 'status', type: 'string', required: false, desc: 'Filter: confirmed, cancelled, checked_in, checked_out' },
        { name: 'check_in_from', type: 'string', required: false, desc: 'Filter check-in from date (YYYY-MM-DD)' },
        { name: 'check_in_to', type: 'string', required: false, desc: 'Filter check-in to date (YYYY-MM-DD)' },
        { name: 'limit', type: 'integer', required: false, desc: 'Max results (default: 100, max: 500)' },
      ],
      detailTitle: 'Reservation Detail',
      detailDesc: 'Get full details of a single reservation by ID or confirmation code.',
      cancelTitle: 'Cancel Reservation',
      cancelDesc: 'Cancel a reservation. Only confirmed/pending reservations can be cancelled.',
      response: 'Response',
    },
    webhooks: {
      heading: 'Webhooks',
      desc: 'Receive real-time notifications when reservation statuses change. Register a webhook URL and Syroce will POST event data to your endpoint.',
      events: 'Supported Events',
      eventList: [
        { name: 'reservation.created', desc: 'A new reservation is created' },
        { name: 'reservation.cancelled', desc: 'A reservation is cancelled' },
        { name: 'reservation.updated', desc: 'A reservation status changes (check-in, check-out)' },
      ],
      registerTitle: 'Register Webhook',
      registerBody: [
        { name: 'url', type: 'string', required: true, desc: 'Your HTTPS endpoint URL' },
        { name: 'events', type: 'array', required: true, desc: 'List of event types to subscribe' },
        { name: 'secret', type: 'string', required: false, desc: 'Signing secret for payload verification' },
      ],
      listTitle: 'List Webhooks',
      deleteTitle: 'Delete Webhook',
      testTitle: 'Test Webhook',
      testDesc: 'Send a test event to your webhook URL.',
      payloadTitle: 'Webhook Payload',
      payloadDesc: 'Each webhook delivery includes these headers and body:',
      securityTitle: 'Verifying Signatures',
      securityDesc: 'If you provide a secret, each delivery includes an X-Webhook-Signature header. Compute HMAC-SHA256 of the raw body with your secret and compare.',
      response: 'Response',
    },
    required: 'required',
    optional: 'optional',
    copyBtn: 'Copy',
    copied: 'Copied!',
    backToApp: 'Back to PMS',
    httpMethods: {
      GET: 'GET',
      POST: 'POST',
      PUT: 'PUT',
      DELETE: 'DELETE',
    },
  },
  tr: {
    title: 'Syroce B2B API',
    subtitle: 'Acente otomasyon sistemleri için entegrasyon dokumantasyonu',
    nav: {
      overview: 'Genel Bakis',
      auth: 'Kimlik Dogrulama',
      content: 'Icerik',
      availability: 'Müsaitlik',
      rates: 'Fiyatlar',
      reservations: 'Rezervasyonlar',
      webhooks: 'Webhook\'lar',
    },
    overview: {
      heading: 'Baslangic',
      desc: 'Syroce B2B API, seyahat acentelerinin otel PMS sistemleriyle dogrudan entegre olmasini saglar. Gercek zamanli müsaitlik sorgulama, fiyat cekme, rezervasyon olusturma ve webhook bildirimleri — hepsi tek bir API uzerinden.',
      baseUrl: 'Temel URL',
      features: 'Temel Ozellikler',
      featureList: [
        'Gercek zamanli oda müsaitlik kontrolu',
        'Acenteye ozel ve temel fiyat sorgulari',
        'Otomatik PMS senkronizasyonlu dogrudan rezervasyon olusturma',
        'Rezervasyon yonetimi (listeleme, detay, iptal)',
        'Durum değişiklikleri için webhook bildirimleri',
      ],
      responseFormat: 'Yanit Formati',
      responseDesc: 'Tum yanitlar JSON formatinda doner. Basarili yanitlar ilgili veri alanlarini icerir. Hata yanitlari bir detail mesaji icerir.',
    },
    auth: {
      heading: 'Kimlik Dogrulama',
      desc: 'Tum B2B API endpoint\'leri bir API key gerektirir. Key\'inizi istek basligina ekleyin:',
      headerName: 'Baslik Adi',
      headerValue: 'Baslik Degeri',
      obtaining: 'API Key Edinme',
      obtainingDesc: 'API key\'ler otel yoneticisi tarafindan Acente Yonetimi panelinden verilir. Erisim talep etmek için otel ortaginizla iletisime gecin.',
      security: 'Guvenlik Notlari',
      securityList: [
        'Key\'ler sunucuda SHA-256 ile hashlenir — asla duz metin olarak saklanmaz',
        'Her key tek bir acenteye ve otel tenant\'ina bagli',
        'Key\'ler otel tarafindan her zaman iptal edilebilir veya yenilenebilir',
        'Kullanim takip edilir (istek sayisi, son kullanim zamani)',
      ],
      errors: 'Kimlik Dogrulama Hatalari',
    },
    content: {
      heading: 'Icerik API',
      desc: 'Oda tipleri, hizmetler ve genel tesis bilgileri dahil otel icerigini getirin. Icerik otel tarafindan acentenize yayinlanmis olmalidir.',
      endpoint: 'Endpoint',
      params: 'Parametreler',
      noParams: 'Sorgu parametresi gerekli degil.',
      response: 'Yanit',
      published: 'Icerik yayinlandiginda',
      notPublished: 'Icerik yayinlanmadiginda',
    },
    availability: {
      heading: 'Müsaitlik API',
      desc: 'Belirtilen tarihler için gercek zamanli oda müsaitligini kontrol edin. Kapasite ve fiyat detaylariyla birlikte tip bazinda müsait oda sayisini dondurur.',
      endpoint: 'Endpoint',
      params: 'Sorgu Parametreleri',
      paramList: [
        { name: 'check_in', type: 'string', required: true, desc: 'Giris tarihi (YYYY-MM-DD)' },
        { name: 'check_out', type: 'string', required: true, desc: 'Cikis tarihi (YYYY-MM-DD)' },
        { name: 'room_type', type: 'string', required: false, desc: 'Oda tipine gore filtrele (opsiyonel)' },
      ],
      response: 'Yanit',
    },
    rates: {
      heading: 'Fiyat API',
      desc: 'Belirtilen tarih araligi için fiyatlari cekin. Yapilandirilmissa acenteye ozel fiyatlari, aksi halde temel otel fiyatlarini dondurur.',
      endpoint: 'Endpoint',
      params: 'Sorgu Parametreleri',
      paramList: [
        { name: 'start_date', type: 'string', required: true, desc: 'Baslangic tarihi (YYYY-MM-DD)' },
        { name: 'end_date', type: 'string', required: true, desc: 'Bitis tarihi (YYYY-MM-DD)' },
        { name: 'room_type', type: 'string', required: false, desc: 'Oda tipine gore filtrele (opsiyonel)' },
      ],
      response: 'Yanit',
    },
    reservations: {
      heading: 'Rezervasyon API',
      desc: 'Rezervasyon oluşturun, listeleyin, goruntuleyin ve iptal edin. Tum rezervasyonlar otomatik olarak otel PMS\'i ile senkronize edilir.',
      createTitle: 'Rezervasyon Olustur',
      createDesc: 'Yeni bir rezervasyon olusturur ve otomatik olarak müsait bir oda atar.',
      bodyParams: 'Istek Govdesi',
      createParams: [
        { name: 'room_type', type: 'string', required: true, desc: 'Oda tipi adi' },
        { name: 'check_in', type: 'string', required: true, desc: 'Giris tarihi (YYYY-MM-DD)' },
        { name: 'check_out', type: 'string', required: true, desc: 'Cikis tarihi (YYYY-MM-DD)' },
        { name: 'guest_name', type: 'string', required: true, desc: 'Misafir tam adi' },
        { name: 'guest_email', type: 'string', required: false, desc: 'Misafir e-posta adresi' },
        { name: 'guest_phone', type: 'string', required: false, desc: 'Misafir telefon numarası' },
        { name: 'adults', type: 'integer', required: false, desc: 'Yetiskin sayisi (varsayilan: 2)' },
        { name: 'children', type: 'integer', required: false, desc: 'Cocuk sayisi (varsayilan: 0)' },
        { name: 'special_requests', type: 'string', required: false, desc: 'Ozel istekler' },
        { name: 'total_amount', type: 'number', required: false, desc: 'Toplam fiyat (0 = otomatik hesapla)' },
      ],
      listTitle: 'Rezervasyonlari Listele',
      listDesc: 'Opsiyonel filtrelerle acente rezervasyonlarinizi getirin.',
      listParams: [
        { name: 'status', type: 'string', required: false, desc: 'Filtre: confirmed, cancelled, checked_in, checked_out' },
        { name: 'check_in_from', type: 'string', required: false, desc: 'Giris tarihinden itibaren filtre (YYYY-MM-DD)' },
        { name: 'check_in_to', type: 'string', required: false, desc: 'Giris tarihine kadar filtre (YYYY-MM-DD)' },
        { name: 'limit', type: 'integer', required: false, desc: 'Maksimum sonuc (varsayilan: 100, maks: 500)' },
      ],
      detailTitle: 'Rezervasyon Detayi',
      detailDesc: 'ID veya onay kodu ile tek bir rezervasyonun tam detaylarini alin.',
      cancelTitle: 'Rezervasyon Iptali',
      cancelDesc: 'Bir rezervasyonu iptal edin. Sadece onaylanmis/bekleyen rezervasyonlar iptal edilebilir.',
      response: 'Yanit',
    },
    webhooks: {
      heading: 'Webhook\'lar',
      desc: 'Rezervasyon durumlari degistiginde gercek zamanli bildirimler alin. Bir webhook URL\'si kaydedin ve Syroce olay verilerini endpoint\'inize POST edecektir.',
      events: 'Desteklenen Olaylar',
      eventList: [
        { name: 'reservation.created', desc: 'Yeni bir rezervasyon oluşturuldugunda' },
        { name: 'reservation.cancelled', desc: 'Bir rezervasyon iptal edildiginde' },
        { name: 'reservation.updated', desc: 'Bir rezervasyon durumu degistiginde (giris, cikis)' },
      ],
      registerTitle: 'Webhook Kaydet',
      registerBody: [
        { name: 'url', type: 'string', required: true, desc: 'HTTPS endpoint URL\'niz' },
        { name: 'events', type: 'array', required: true, desc: 'Abone olunacak olay tipleri listesi' },
        { name: 'secret', type: 'string', required: false, desc: 'Payload dogrulamasi için imzalama anahtari' },
      ],
      listTitle: 'Webhook\'lari Listele',
      deleteTitle: 'Webhook Sil',
      testTitle: 'Webhook Test Et',
      testDesc: 'Webhook URL\'nize bir test olayi gonderin.',
      payloadTitle: 'Webhook Payload',
      payloadDesc: 'Her webhook teslimati su baslik ve govdeyi icerir:',
      securityTitle: 'Imza Dogrulama',
      securityDesc: 'Bir secret belirlerseniz, her teslimat X-Webhook-Signature basligini icerir. Ham gövdenin HMAC-SHA256\'sini secret\'inizle hesaplayin ve karsilastirin.',
      response: 'Yanit',
    },
    required: 'zorunlu',
    optional: 'opsiyonel',
    copyBtn: 'Kopyala',
    copied: 'Kopyalandi!',
    backToApp: 'PMS\'e Don',
    httpMethods: {
      GET: 'GET',
      POST: 'POST',
      PUT: 'PUT',
      DELETE: 'DELETE',
    },
  },
};

const CodeBlock = ({ code, lang = 'bash' }) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <div className="relative group rounded-lg overflow-hidden border border-slate-700 bg-[#0d1117]">
      <div className="flex items-center justify-between px-4 py-2 bg-[#161b22] border-b border-slate-700">
        <span className="text-xs text-slate-400 font-mono">{lang}</span>
        <button
          onClick={handleCopy}
          className="text-xs text-slate-400 hover:text-white transition flex items-center gap-1"
          data-testid="code-copy-btn"
        >
          {copied ? <Check size={12} /> : <Copy size={12} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-sm leading-relaxed">
        <code className="text-slate-200 font-mono text-[13px]">{code}</code>
      </pre>
    </div>
  );
};

const ParamTable = ({ params, t }) => (
  <div className="overflow-x-auto rounded-lg border border-slate-200">
    <table className="w-full text-sm">
      <thead>
        <tr className="bg-slate-50 border-b border-slate-200">
          <th className="text-left px-4 py-2.5 font-semibold text-slate-700">Parameter</th>
          <th className="text-left px-4 py-2.5 font-semibold text-slate-700">Type</th>
          <th className="text-left px-4 py-2.5 font-semibold text-slate-700">Required</th>
          <th className="text-left px-4 py-2.5 font-semibold text-slate-700">Description</th>
        </tr>
      </thead>
      <tbody>
        {params.map((p, i) => (
          <tr key={p.name} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
            <td className="px-4 py-2.5 font-mono text-[13px] text-emerald-700">{p.name}</td>
            <td className="px-4 py-2.5 text-slate-500 font-mono text-[13px]">{p.type}</td>
            <td className="px-4 py-2.5">
              {p.required
                ? <span className="text-xs font-medium text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full">{t.required}</span>
                : <span className="text-xs text-slate-400">{t.optional}</span>
              }
            </td>
            <td className="px-4 py-2.5 text-slate-600">{p.desc}</td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

const MethodBadge = ({ method }) => {
  const colors = {
    GET: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    POST: 'bg-blue-100 text-blue-800 border-blue-200',
    PUT: 'bg-amber-100 text-amber-800 border-amber-200',
    DELETE: 'bg-red-100 text-red-800 border-red-200',
  };
  return (
    <span className={`inline-block px-2.5 py-1 rounded font-mono text-xs font-bold border ${colors[method] || 'bg-slate-100 text-slate-700'}`}>
      {method}
    </span>
  );
};

const EndpointBlock = ({ method, path, children }) => (
  <div className="rounded-lg border border-slate-200 bg-white overflow-hidden">
    <div className="flex items-center gap-3 px-4 py-3 bg-slate-50 border-b border-slate-200">
      <MethodBadge method={method} />
      <code className="text-sm font-mono text-slate-800">{path}</code>
    </div>
    <div className="p-5 space-y-4">{children}</div>
  </div>
);

const SectionHeader = ({ icon: Icon, title, id }) => (
  <h2 id={id} className="text-2xl font-bold text-slate-900 flex items-center gap-3 pt-8 pb-2 scroll-mt-20" style={{ fontFamily: 'Manrope, sans-serif' }}>
    <div className="w-9 h-9 rounded-lg bg-[#C09D63]/10 flex items-center justify-center">
      <Icon size={18} className="text-[#C09D63]" />
    </div>
    {title}
  </h2>
);

export default function B2BApiDocs() {
  const [lang, setLang] = useState('en');
  const [activeSection, setActiveSection] = useState('overview');
  const t = translations[lang];

  useEffect(() => {
    const handleScroll = () => {
      const sections = ['overview', 'auth', 'content', 'availability', 'rates', 'reservations', 'webhooks'];
      for (const id of sections) {
        const el = document.getElementById(id);
        if (el) {
          const rect = el.getBoundingClientRect();
          if (rect.top <= 120) {
            setActiveSection(id);
          }
        }
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollTo = (id) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const navItems = [
    { id: 'overview', icon: BookOpen, label: t.nav.overview },
    { id: 'auth', icon: Key, label: t.nav.auth },
    { id: 'content', icon: Hotel, label: t.nav.content },
    { id: 'availability', icon: Calendar, label: t.nav.availability },
    { id: 'rates', icon: DollarSign, label: t.nav.rates },
    { id: 'reservations', icon: FileText, label: t.nav.reservations },
    { id: 'webhooks', icon: Bell, label: t.nav.webhooks },
  ];

  return (
    <div className="min-h-screen bg-white" data-testid="b2b-api-docs">
      <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet" />

      {/* Top Bar */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-slate-900 border-b border-slate-700/50 h-14">
        <div className="flex items-center justify-between h-full px-6 max-w-[1600px] mx-auto">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-md bg-[#C09D63] flex items-center justify-center">
                <Code size={14} className="text-white" />
              </div>
              <span className="text-white font-bold text-lg" style={{ fontFamily: 'Manrope, sans-serif' }}>
                {t.title}
              </span>
            </div>
            <span className="hidden md:block text-slate-400 text-sm border-l border-slate-600 pl-4 ml-2">
              {t.subtitle}
            </span>
          </div>
          <div className="flex items-center gap-3">
            {/* Language Toggle */}
            <div className="flex items-center bg-slate-800 rounded-lg p-0.5" data-testid="lang-toggle">
              <button
                onClick={() => setLang('en')}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${lang === 'en' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-400 hover:text-white'}`}
                data-testid="lang-en-btn"
              >
                EN
              </button>
              <button
                onClick={() => setLang('tr')}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all flex items-center gap-1 ${lang === 'tr' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-400 hover:text-white'}`}
                data-testid="lang-tr-btn"
              >
                TR
              </button>
            </div>
          </div>
        </div>
      </header>

      <div className="flex pt-14">
        {/* Sidebar Navigation */}
        <aside className="hidden lg:block fixed left-0 top-14 bottom-0 w-60 bg-slate-50 border-r border-slate-200 overflow-y-auto">
          <nav className="py-6 px-3">
            <div className="space-y-1">
              {navItems.map(({ id, icon: Icon, label }) => (
                <button
                  key={id}
                  onClick={() => scrollTo(id)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg text-sm flex items-center gap-2.5 transition-all ${
                    activeSection === id
                      ? 'bg-white shadow-sm border border-slate-200 text-slate-900 font-semibold'
                      : 'text-slate-500 hover:text-slate-800 hover:bg-white/60'
                  }`}
                  data-testid={`nav-${id}`}
                >
                  <Icon size={15} className={activeSection === id ? 'text-[#C09D63]' : 'text-slate-400'} />
                  {label}
                </button>
              ))}
            </div>
          </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 lg:ml-60 min-h-screen">
          <div className="max-w-4xl mx-auto px-6 md:px-10 py-10 space-y-12">

            {/* ── Overview ── */}
            <section id="overview">
              <SectionHeader icon={BookOpen} title={t.overview.heading} id="overview-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.overview.desc}</p>

              <div className="mt-6 space-y-4">
                <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wider">{t.overview.baseUrl}</h3>
                <CodeBlock code={API_BASE} lang="url" />
              </div>

              <div className="mt-8">
                <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wider mb-3">{t.overview.features}</h3>
                <div className="grid gap-2">
                  {t.overview.featureList.map((f, i) => (
                    <div key={i} className="flex items-center gap-3 text-sm text-slate-600">
                      <div className="w-5 h-5 rounded-full bg-emerald-100 flex items-center justify-center shrink-0">
                        <Check size={12} className="text-emerald-600" />
                      </div>
                      {f}
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-8">
                <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wider mb-3">{t.overview.responseFormat}</h3>
                <p className="text-sm text-slate-600 mb-3">{t.overview.responseDesc}</p>
                <CodeBlock lang="json" code={`// Success
{
  "check_in": "2026-03-15",
  "check_out": "2026-03-18",
  "room_types": [...]
}

// Error
{
  "detail": "Gecersiz veya devre dışı API key"
}`} />
              </div>
            </section>

            {/* ── Authentication ── */}
            <section id="auth">
              <SectionHeader icon={Key} title={t.auth.heading} id="auth-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.auth.desc}</p>

              <div className="mt-4">
                <CodeBlock lang="http" code={`X-API-Key: syroce_b2b_your_api_key_here`} />
              </div>

              <div className="mt-4">
                <CodeBlock lang="bash" code={`curl -X GET "${API_BASE}/content" \\
  -H "X-API-Key: syroce_b2b_your_api_key_here"`} />
              </div>

              <div className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-5">
                <h4 className="font-semibold text-blue-900 flex items-center gap-2 text-sm">
                  <Shield size={15} /> {t.auth.obtaining}
                </h4>
                <p className="text-sm text-blue-800 mt-2">{t.auth.obtainingDesc}</p>
              </div>

              <div className="mt-6">
                <h4 className="font-semibold text-slate-700 text-sm mb-3">{t.auth.security}</h4>
                <div className="space-y-2">
                  {t.auth.securityList.map((note, i) => (
                    <div key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                      <Shield size={13} className="text-slate-400 mt-0.5 shrink-0" />
                      {note}
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-6">
                <h4 className="font-semibold text-slate-700 text-sm mb-3">{t.auth.errors}</h4>
                <CodeBlock lang="json" code={`// 401 Unauthorized
{ "detail": "Gecersiz veya devre dışı API key" }

// 403 Forbidden
{ "detail": "Acente hesabi aktif değil" }`} />
              </div>
            </section>

            {/* ── Content ── */}
            <section id="content">
              <SectionHeader icon={Hotel} title={t.content.heading} id="content-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.content.desc}</p>

              <div className="mt-6">
                <EndpointBlock method="GET" path="/api/b2b/content">
                  <p className="text-sm text-slate-500">{t.content.noParams}</p>
                  <h4 className="font-semibold text-sm text-slate-700 mt-4">{t.content.response}</h4>
                  <CodeBlock lang="json" code={`// ${t.content.published}
{
  "published": true,
  "hotel_content": {
    "hotel_name": "Grand Palace Hotel",
    "star_rating": 5,
    "room_types": [...],
    "services": [...],
    "policies": {...}
  }
}

// ${t.content.notPublished}
{
  "published": false,
  "message": "Bu acente için henüz icerik yayinlanmamis",
  "hotel_content": null
}`} />
                </EndpointBlock>
              </div>
            </section>

            {/* ── Availability ── */}
            <section id="availability">
              <SectionHeader icon={Calendar} title={t.availability.heading} id="avail-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.availability.desc}</p>

              <div className="mt-6">
                <EndpointBlock method="GET" path="/api/b2b/availability?check_in=2026-03-15&check_out=2026-03-18">
                  <h4 className="font-semibold text-sm text-slate-700">{t.availability.params}</h4>
                  <ParamTable params={t.availability.paramList} t={t} />

                  <h4 className="font-semibold text-sm text-slate-700 mt-4">{t.availability.response}</h4>
                  <CodeBlock lang="json" code={`{
  "check_in": "2026-03-15",
  "check_out": "2026-03-18",
  "room_types": [
    {
      "room_type": "Deluxe Double",
      "capacity": 3,
      "base_price": 250.00,
      "amenities": ["wifi", "minibar", "sea_view"],
      "bed_type": "king",
      "total_rooms": 10,
      "available_rooms": 6
    }
  ]
}`} />
                </EndpointBlock>
              </div>
            </section>

            {/* ── Rates ── */}
            <section id="rates">
              <SectionHeader icon={DollarSign} title={t.rates.heading} id="rates-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.rates.desc}</p>

              <div className="mt-6">
                <EndpointBlock method="GET" path="/api/b2b/rates?start_date=2026-03-15&end_date=2026-03-18">
                  <h4 className="font-semibold text-sm text-slate-700">{t.rates.params}</h4>
                  <ParamTable params={t.rates.paramList} t={t} />

                  <h4 className="font-semibold text-sm text-slate-700 mt-4">{t.rates.response}</h4>
                  <CodeBlock lang="json" code={`{
  "start_date": "2026-03-15",
  "end_date": "2026-03-18",
  "source": "agency_rates",
  "rates": [
    {
      "date": "2026-03-15",
      "room_type_code": "DLX",
      "single": 200.00,
      "double": 250.00,
      "triple": 300.00,
      "currency": "TRY"
    }
  ]
}`} />
                </EndpointBlock>
              </div>
            </section>

            {/* ── Reservations ── */}
            <section id="reservations">
              <SectionHeader icon={FileText} title={t.reservations.heading} id="res-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.reservations.desc}</p>

              <div className="mt-6 space-y-6">
                {/* Create */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.reservations.createTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.reservations.createDesc}</p>
                  <EndpointBlock method="POST" path="/api/b2b/reservations">
                    <h4 className="font-semibold text-sm text-slate-700">{t.reservations.bodyParams}</h4>
                    <ParamTable params={t.reservations.createParams} t={t} />

                    <h4 className="font-semibold text-sm text-slate-700 mt-4">{t.reservations.response}</h4>
                    <CodeBlock lang="json" code={`{
  "ok": true,
  "reservation": {
    "id": "a1b2c3d4-...",
    "confirmation_code": "B2B-A1B2C3D4",
    "status": "confirmed",
    "room_type": "Deluxe Double",
    "room_number": "302",
    "check_in": "2026-03-15",
    "check_out": "2026-03-18",
    "guest_name": "John Doe",
    "total_amount": 750.00,
    "commission_rate": 10,
    "commission_amount": 75.00,
    "created_at": "2026-03-10T14:30:00+00:00"
  },
  "message": "Rezervasyon oluşturuldu: B2B-A1B2C3D4"
}`} />
                  </EndpointBlock>
                </div>

                {/* List */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.reservations.listTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.reservations.listDesc}</p>
                  <EndpointBlock method="GET" path="/api/b2b/reservations?status=confirmed&limit=50">
                    <h4 className="font-semibold text-sm text-slate-700">Query Parameters</h4>
                    <ParamTable params={t.reservations.listParams} t={t} />
                  </EndpointBlock>
                </div>

                {/* Detail */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.reservations.detailTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.reservations.detailDesc}</p>
                  <EndpointBlock method="GET" path="/api/b2b/reservations/{reservation_id}" />
                </div>

                {/* Cancel */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.reservations.cancelTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.reservations.cancelDesc}</p>
                  <EndpointBlock method="PUT" path="/api/b2b/reservations/{reservation_id}/cancel">
                    <h4 className="font-semibold text-sm text-slate-700 mt-2">{t.reservations.response}</h4>
                    <CodeBlock lang="json" code={`{
  "ok": true,
  "reservation_id": "a1b2c3d4-...",
  "confirmation_code": "B2B-A1B2C3D4",
  "status": "cancelled",
  "message": "Rezervasyon iptal edildi"
}`} />
                  </EndpointBlock>
                </div>
              </div>
            </section>

            {/* ── Webhooks ── */}
            <section id="webhooks">
              <SectionHeader icon={Bell} title={t.webhooks.heading} id="wh-h" />
              <p className="text-slate-600 leading-relaxed mt-3">{t.webhooks.desc}</p>

              <div className="mt-6">
                <h3 className="text-sm font-semibold text-slate-700 uppercase tracking-wider mb-3">{t.webhooks.events}</h3>
                <div className="space-y-2">
                  {t.webhooks.eventList.map((ev) => (
                    <div key={ev.name} className="flex items-center gap-3 bg-slate-50 rounded-lg px-4 py-3 border border-slate-200">
                      <code className="text-xs font-mono bg-white px-2 py-1 rounded border border-slate-200 text-[#C09D63] font-semibold">{ev.name}</code>
                      <span className="text-sm text-slate-600">{ev.desc}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-8 space-y-6">
                {/* Register */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.webhooks.registerTitle}</h3>
                  <EndpointBlock method="POST" path="/api/b2b/webhooks">
                    <ParamTable params={t.webhooks.registerBody} t={t} />
                    <CodeBlock lang="bash" code={`curl -X POST "${API_BASE}/webhooks" \\
  -H "X-API-Key: syroce_b2b_your_key" \\
  -H "Content-Type: application/json" \\
  -d '{
    "url": "https://your-agency.com/webhook",
    "events": ["reservation.created", "reservation.cancelled"],
    "secret": "your_signing_secret"
  }'`} />
                  </EndpointBlock>
                </div>

                {/* List */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.webhooks.listTitle}</h3>
                  <EndpointBlock method="GET" path="/api/b2b/webhooks" />
                </div>

                {/* Delete */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.webhooks.deleteTitle}</h3>
                  <EndpointBlock method="DELETE" path="/api/b2b/webhooks/{webhook_id}" />
                </div>

                {/* Test */}
                <div>
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.webhooks.testTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.webhooks.testDesc}</p>
                  <EndpointBlock method="POST" path="/api/b2b/webhooks/{webhook_id}/test" />
                </div>

                {/* Payload */}
                <div className="mt-8">
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">{t.webhooks.payloadTitle}</h3>
                  <p className="text-sm text-slate-500 mb-4">{t.webhooks.payloadDesc}</p>
                  <CodeBlock lang="http" code={`POST /webhook HTTP/1.1
Content-Type: application/json
X-Webhook-Event: reservation.created
X-Webhook-Signature: sha256=abc123...
X-Webhook-Delivery: d1e2f3a4-...`} />

                  <div className="mt-3">
                    <CodeBlock lang="json" code={`{
  "event": "reservation.created",
  "timestamp": "2026-03-10T14:30:00+00:00",
  "delivery_id": "d1e2f3a4-...",
  "data": {
    "reservation_id": "a1b2c3d4-...",
    "confirmation_code": "B2B-A1B2C3D4",
    "status": "confirmed",
    "room_type": "Deluxe Double",
    "check_in": "2026-03-15",
    "check_out": "2026-03-18",
    "guest_name": "John Doe",
    "total_amount": 750.00
  }
}`} />
                  </div>
                </div>

                {/* Signature Verification */}
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-5 mt-6">
                  <h4 className="font-semibold text-amber-900 flex items-center gap-2 text-sm">
                    <Shield size={15} /> {t.webhooks.securityTitle}
                  </h4>
                  <p className="text-sm text-amber-800 mt-2">{t.webhooks.securityDesc}</p>
                  <div className="mt-3">
                    <CodeBlock lang="python" code={`import hmac, hashlib

def verify_signature(payload_body, secret, signature_header):
    expected = hmac.new(
        secret.encode(), payload_body, hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(f"sha256={expected}", signature_header)`} />
                  </div>
                </div>
              </div>
            </section>

            {/* Footer */}
            <div className="border-t border-slate-200 pt-8 pb-16 text-center">
              <p className="text-sm text-slate-400">
                Syroce B2B API v1.0 &middot; {new Date().getFullYear()}
              </p>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
