import {
  Sparkles, Wrench, Wifi, Tv, Thermometer, Utensils, Wine, Beer, Shirt,
  Car, Bell, Heart, Package, MessageSquare, AlertTriangle, Hotel, CheckCircle2, Loader2
} from "lucide-react";

export const ICONS = {
  sparkles: Sparkles, wrench: Wrench, wifi: Wifi, tv: Tv, thermometer: Thermometer,
  utensils: Utensils, wine: Wine, beer: Beer, shirt: Shirt, car: Car, bell: Bell,
  heart: Heart, package: Package, message: MessageSquare, alert: AlertTriangle,
  check: CheckCircle2, loader: Loader2, hotel: Hotel
};

export const LANGS = [
  { code: "tr", label: "Türkçe" },
  { code: "en", label: "English" },
  { code: "de", label: "Deutsch" },
  { code: "ru", label: "Русский" },
  { code: "ar", label: "العربية" },
];

export const EXPERIENCE_COPY = {
  tr: {
    guestServices: "Misafir Hizmetleri",
    heroSubtitle: "Konaklamanız boyunca yanınızdayız.",
    pickTitle: "Size nasıl yardımcı olabiliriz?",
    pickHint: "İhtiyacınız olan hizmeti seçin; talebinizi doğru ekibe hemen iletelim.",
    serviceHint: "Hizmeti seçin ve gerekiyorsa ayrıntıları ekleyin.",
    secureNote: "Talebiniz güvenli şekilde otel ekibine iletilir.",
    serviceAdd: "Talebe ekle",
    serviceAdded: "Eklendi",
    departmentFallback: "Otel hizmetleri ve destek",
  },
  en: {
    guestServices: "Guest Services",
    heroSubtitle: "We are here throughout your stay.",
    pickTitle: "How may we assist you?",
    pickHint: "Choose a service and we will route your request to the right hotel team.",
    serviceHint: "Select a service and add details when needed.",
    secureNote: "Your request is securely delivered to the hotel team.",
    serviceAdd: "Add to request",
    serviceAdded: "Added",
    departmentFallback: "Hotel services and assistance",
  },
  de: {
    guestServices: "Gästeservice",
    heroSubtitle: "Wir sind während Ihres Aufenthalts für Sie da.",
    pickTitle: "Wie können wir Ihnen helfen?",
    pickHint: "Wählen Sie einen Service; wir leiten Ihre Anfrage an das zuständige Hotelteam weiter.",
    serviceHint: "Wählen Sie einen Service und ergänzen Sie bei Bedarf Details.",
    secureNote: "Ihre Anfrage wird sicher an das Hotelteam übermittelt.",
    serviceAdd: "Zur Anfrage hinzufügen",
    serviceAdded: "Hinzugefügt",
    departmentFallback: "Hotelservice und Unterstützung",
  },
  ru: {
    guestServices: "Гостевой сервис",
    heroSubtitle: "Мы рядом на протяжении всего вашего проживания.",
    pickTitle: "Чем мы можем помочь?",
    pickHint: "Выберите услугу, и мы направим запрос нужной команде отеля.",
    serviceHint: "Выберите услугу и при необходимости добавьте детали.",
    secureNote: "Ваш запрос будет безопасно передан команде отеля.",
    serviceAdd: "Добавить в запрос",
    serviceAdded: "Добавлено",
    departmentFallback: "Услуги и помощь в отеле",
  },
  ar: {
    guestServices: "خدمات الضيوف",
    heroSubtitle: "نحن إلى جانبك طوال فترة إقامتك.",
    pickTitle: "كيف يمكننا مساعدتك؟",
    pickHint: "اختر الخدمة وسنرسل طلبك مباشرة إلى فريق الفندق المختص.",
    serviceHint: "اختر الخدمة وأضف التفاصيل عند الحاجة.",
    secureNote: "يتم إرسال طلبك بأمان إلى فريق الفندق.",
    serviceAdd: "إضافة إلى الطلب",
    serviceAdded: "تمت الإضافة",
    departmentFallback: "خدمات الفندق والمساعدة",
  },
};

export const DEPT_DESCRIPTIONS = {
  tr: {
    housekeeping: "Temizlik, havlu ve oda ihtiyaçları",
    rooms: "Temizlik, havlu ve oda ihtiyaçları",
    technical: "Klima, Wi-Fi ve teknik destek",
    reception: "Resepsiyon ve konaklama talepleri",
    other: "Resepsiyon ve konaklama talepleri",
    fnb: "Yeme, içme ve oda servisi",
    laundry: "Çamaşır ve kuru temizleme",
    transportation: "Transfer ve ulaşım desteği",
    spa: "SPA ve bakım hizmetleri",
    minibar: "Minibar talep ve desteği",
  },
  en: {
    housekeeping: "Cleaning, towels and room essentials",
    rooms: "Cleaning, towels and room essentials",
    technical: "Air conditioning, Wi-Fi and maintenance",
    reception: "Front desk and stay assistance",
    other: "Front desk and stay assistance",
    fnb: "Dining and in-room service",
    laundry: "Laundry and dry cleaning",
    transportation: "Transfers and transportation",
    spa: "Spa and wellness services",
    minibar: "Minibar requests and assistance",
  },
  de: {
    housekeeping: "Reinigung, Handtücher und Zimmerbedarf",
    rooms: "Reinigung, Handtücher und Zimmerbedarf",
    technical: "Klimaanlage, WLAN und technische Hilfe",
    reception: "Rezeption und Unterstützung während des Aufenthalts",
    other: "Rezeption und Unterstützung während des Aufenthalts",
    fnb: "Gastronomie und Zimmerservice",
    laundry: "Wäsche- und Reinigungsservice",
    transportation: "Transfer- und Transportservice",
    spa: "Spa- und Wellnessangebote",
    minibar: "Minibar-Anfragen und Unterstützung",
  },
  ru: {
    housekeeping: "Уборка, полотенца и всё необходимое для номера",
    rooms: "Уборка, полотенца и всё необходимое для номера",
    technical: "Кондиционер, Wi-Fi и техническая помощь",
    reception: "Стойка регистрации и помощь во время проживания",
    other: "Стойка регистрации и помощь во время проживания",
    fnb: "Питание и обслуживание в номере",
    laundry: "Стирка и химчистка",
    transportation: "Трансфер и транспорт",
    spa: "Спа- и велнес-услуги",
    minibar: "Запросы по мини-бару и помощь",
  },
  ar: {
    housekeeping: "التنظيف والمناشف واحتياجات الغرفة",
    rooms: "التنظيف والمناشف واحتياجات الغرفة",
    technical: "التكييف والواي فاي والدعم الفني",
    reception: "الاستقبال والمساعدة أثناء الإقامة",
    other: "الاستقبال والمساعدة أثناء الإقامة",
    fnb: "الطعام وخدمة الغرف",
    laundry: "الغسيل والتنظيف الجاف",
    transportation: "خدمات النقل والمواصلات",
    spa: "خدمات السبا والعافية",
    minibar: "طلبات الميني بار والمساعدة",
  },
};

export const UI = {
  tr: { title: "Oda Talebi", room: "Oda", welcome: "Hoş geldiniz", pick: "Ne için talep oluşturuyorsunuz?",
        describe: "Detay / Açıklama", placeholder: "Kısaca talebinizi yazın...", priority: "Öncelik",
        low: "Düşük", normal: "Normal", high: "Yüksek", urgent: "Acil", submit: "Talebi Gönder",
        sent: "Talebiniz alındı!", sentDesc: "İlgili departmana iletildi, kısa sürede geri dönülecek.",
        newReq: "Yeni talep oluştur", name: "Adınız (opsiyonel)", phone: "Telefon (opsiyonel)",
        sending: "Gönderiliyor...", language: "Dil", back: "Geri", home: "Ana menü",
        errorTitle: "Talep açılamadı", unavailableTitle: "Hizmet Kullanılamıyor", unavailableDesc: "Bu oda için aktif bir konaklama bulunamadı veya oturumunuz sona erdi.",
        loadError: "Yükleme hatası", sendError: "Gönderim hatası",
        conversation: "Mesajlar", you: "Siz", team: "Otel Ekibi",
        replyPlaceholder: "Bir mesaj yazın...", send: "Gönder", noMessages: "Henüz mesaj yok.",
        reviewReq: "Talebi İncele", items: "seçim", addNote: "Not Ekle (opsiyonel)",
        chargeWarning: "Bu hizmet ek ücrete tabi olabilir.", emptyCart: "Sepetiniz boş",
        qty: "Adet", remove: "Kaldır", addMore: "Daha fazla ekle", rateLimit: "Çok fazla istek gönderildi, lütfen biraz bekleyin.",
        structuredSentDesc: "Talebiniz başarıyla alındı ve ilgili ekiplere iletildi.",
        requestSummary: "Otel ekibine iletilen talebiniz",
        selectOption: "Seçim yapınız", date: "Tarih", time: "Saat", datetime: "Tarih & Saat",
        unsupportedInput: "Bu hizmet türü şu an desteklenmiyor.", conflictError: "Talebiniz daha önce işlenmiş olabilir veya güncellendi. Lütfen tekrar deneyin.",
        tryAgain: "Tekrar Dene", networkError: "Bağlantı hatası oluştu, lütfen internetinizi kontrol edip tekrar deneyin." },
  en: { title: "Room Request", room: "Room", welcome: "Welcome", pick: "What is your request about?",
        describe: "Details", placeholder: "Briefly describe your request...", priority: "Priority",
        low: "Low", normal: "Normal", high: "High", urgent: "Urgent", submit: "Submit Request",
        sent: "Request received!", sentDesc: "It has been forwarded to the right team. We'll get back to you shortly.",
        newReq: "Make another request", name: "Your name (optional)", phone: "Phone (optional)",
        sending: "Sending...", language: "Language", back: "Back", home: "Main menu",
        errorTitle: "Unable to open request", unavailableTitle: "Service Unavailable", unavailableDesc: "No active stay found for this room or your session has expired.",
        loadError: "Loading error", sendError: "Sending error",
        conversation: "Messages", you: "You", team: "Hotel Team",
        replyPlaceholder: "Write a message...", send: "Send", noMessages: "No messages yet.",
        reviewReq: "Review Request", items: "items", addNote: "Add Note (optional)",
        chargeWarning: "This service may be subject to an additional charge.", emptyCart: "Your cart is empty",
        qty: "Qty", remove: "Remove", addMore: "Add more", rateLimit: "Too many requests, please wait.",
        structuredSentDesc: "Your request has been successfully received.",
        requestSummary: "Your request to the hotel team",
        selectOption: "Select an option", date: "Date", time: "Time", datetime: "Date & Time",
        unsupportedInput: "This service type is currently unsupported.", conflictError: "Your request may have already been processed or updated. Please try again.",
        tryAgain: "Try Again", networkError: "Network error occurred, please check your connection and try again." },
  de: { title: "Zimmeranfrage", room: "Zimmer", welcome: "Willkommen", pick: "Worum geht es?",
        describe: "Beschreibung", placeholder: "Beschreiben Sie Ihre Anfrage...", priority: "Priorität",
        low: "Niedrig", normal: "Normal", high: "Hoch", urgent: "Dringend", submit: "Anfrage senden",
        sent: "Anfrage erhalten!", sentDesc: "Wir haben sie an das Team weitergeleitet.",
        newReq: "Neue Anfrage", name: "Name (optional)", phone: "Telefon (optional)",
        sending: "Senden...", language: "Sprache", back: "Zurück", home: "Hauptmenü",
        errorTitle: "Anfrage konnte nicht geöffnet werden", unavailableTitle: "Dienst nicht verfügbar", unavailableDesc: "Für dieses Zimmer wurde kein aktiver Aufenthalt gefunden oder Ihre Sitzung ist abgelaufen.",
        loadError: "Ladefehler", sendError: "Sendefehler",
        conversation: "Nachrichten", you: "Sie", team: "Hotel-Team",
        replyPlaceholder: "Nachricht schreiben...", send: "Senden", noMessages: "Noch keine Nachrichten.",
        reviewReq: "Anfrage überprüfen", items: "Elemente", addNote: "Notiz hinzufügen (optional)",
        chargeWarning: "Für diesen Service können zusätzliche Gebühren anfallen.", emptyCart: "Ihr Warenkorb ist leer",
        qty: "Menge", remove: "Entfernen", addMore: "Mehr hinzufügen", rateLimit: "Zu viele Anfragen, bitte warten Sie.",
        structuredSentDesc: "Ihre Anfrage wurde erfolgreich empfangen.",
        requestSummary: "Ihre Anfrage an das Hotelteam",
        selectOption: "Wählen Sie eine Option", date: "Datum", time: "Zeit", datetime: "Datum & Zeit",
        unsupportedInput: "Dieser Servicetyp wird derzeit nicht unterstützt.", conflictError: "Ihre Anfrage wurde möglicherweise bereits verarbeitet. Bitte versuchen Sie es erneut.",
        tryAgain: "Erneut versuchen", networkError: "Netzwerkfehler aufgetreten, bitte überprüfen Sie Ihre Verbindung." },
  ru: { title: "Запрос из номера", room: "Номер", welcome: "Добро пожаловать", pick: "Что вас интересует?",
        describe: "Описание", placeholder: "Опишите ваш запрос...", priority: "Приоритет",
        low: "Низкий", normal: "Обычный", high: "Высокий", urgent: "Срочно", submit: "Отправить",
        sent: "Запрос принят!", sentDesc: "Мы передали его в нужный отдел.",
        newReq: "Новый запрос", name: "Имя (необяз.)", phone: "Телефон (необяз.)",
        sending: "Отправка...", language: "Язык", back: "Назад", home: "Главное меню",
        errorTitle: "Не удалось открыть запрос", unavailableTitle: "Услуга недоступна", unavailableDesc: "Активное проживание для этого номера не найдено или срок действия вашего сеанса истек.",
        loadError: "Ошибка загрузки", sendError: "Ошибка отправки",
        conversation: "Сообщения", you: "Вы", team: "Команда отеля",
        replyPlaceholder: "Напишите сообщение...", send: "Отправить", noMessages: "Сообщений пока нет.",
        reviewReq: "Проверить запрос", items: "предметы", addNote: "Добавить примечание (необязательно)",
        chargeWarning: "За эту услугу может взиматься дополнительная плата.", emptyCart: "Ваша корзина пуста",
        qty: "Кол-во", remove: "Удалить", addMore: "Добавить еще", rateLimit: "Слишком много запросов, пожалуйста, подождите.",
        structuredSentDesc: "Ваш запрос успешно получен.",
        requestSummary: "Ваш запрос команде отеля",
        selectOption: "Выберите опцию", date: "Дата", time: "Время", datetime: "Дата и время",
        unsupportedInput: "Этот тип услуги в настоящее время не поддерживается.", conflictError: "Ваш запрос, возможно, уже был обработан. Пожалуйста, попробуйте еще раз.",
        tryAgain: "Попробовать снова", networkError: "Произошла ошибка сети, пожалуйста, проверьте подключение." },
  ar: { title: "طلب من الغرفة", room: "غرفة", welcome: "أهلاً بك", pick: "ما هو طلبك؟",
        describe: "التفاصيل", placeholder: "صف طلبك...", priority: "الأولوية",
        low: "منخفض", normal: "عادي", high: "مرتفع", urgent: "عاجل", submit: "إرسال الطلب",
        sent: "تم استلام طلبك!", sentDesc: "تم تحويله إلى القسم المختص.",
        newReq: "طلب جديد", name: "الاسم (اختياري)", phone: "الهاتف (اختياري)",
        sending: "جارٍ الإرسال...", language: "اللغة", back: "رجوع", home: "القائمة الرئيسية",
        errorTitle: "تعذّر فتح الطلب", unavailableTitle: "الخدمة غير متوفرة", unavailableDesc: "لم يتم العثور على إقامة نشطة لهذه الغرفة أو انتهت صلاحية جلستك.",
        loadError: "خطأ في التحميل", sendError: "خطأ في الإرسال",
        conversation: "الرسائل", you: "أنت", team: "فريق الفندق",
        replyPlaceholder: "اكتب رسالة...", send: "إرسال", noMessages: "لا توجد رسائل بعد.",
        reviewReq: "مراجعة الطلب", items: "عناصر", addNote: "إضافة ملاحظة (اختياري)",
        chargeWarning: "قد تخضع هذه الخدمة لرسوم إضافية.", emptyCart: "عربة التسوق فارغة",
        qty: "الكمية", remove: "إزالة", addMore: "أضف المزيد", rateLimit: "طلبات كثيرة جدًا، يرجى الانتظار.",
        structuredSentDesc: "تم استلام طلبك بنجاح.",
        requestSummary: "طلبك إلى فريق الفندق",
        selectOption: "حدد خيارا", date: "تاريخ", time: "وقت", datetime: "التاريخ والوقت",
        unsupportedInput: "نوع الخدمة هذا غير مدعوم حاليًا.", conflictError: "ربما تمت معالجة طلبك بالفعل. يرجى المحاولة مرة أخرى.",
        tryAgain: "حاول مرة أخرى", networkError: "حدث خطأ في الشبكة، يرجى التحقق من اتصالك." },
};

export const LOCALE = { tr: "tr-TR", en: "en-US", de: "de-DE", ru: "ru-RU", ar: "ar" };

export const DEPT_LABELS = {
  tr: { housekeeping: "Kat Hizmetleri", rooms: "Kat Hizmetleri", technical: "Teknik Servis", reception: "Resepsiyon", fnb: "Restoran / Oda Servisi", laundry: "Çamaşırhane", transportation: "Ulaşım", spa: "SPA", other: "Resepsiyon / Diğer", minibar: "Minibar" },
  en: { housekeeping: "Housekeeping", rooms: "Housekeeping", technical: "Maintenance", reception: "Reception", fnb: "Dining & Room Service", laundry: "Laundry", transportation: "Transportation", spa: "SPA", other: "Reception / Other", minibar: "Minibar" },
  de: { housekeeping: "Zimmerreinigung", rooms: "Zimmerreinigung", technical: "Wartung", reception: "Rezeption", fnb: "Restaurant", laundry: "Wäscherei", transportation: "Transport", spa: "SPA", other: "Rezeption / Andere", minibar: "Minibar" },
  ru: { housekeeping: "Уборка", rooms: "Уборка", technical: "Ремонт", reception: "Ресепшн", fnb: "Ресторан", laundry: "Прачечная", transportation: "Транспорт", spa: "СПА", other: "Ресепшн / Другое", minibar: "Минибар" },
  ar: { housekeeping: "خدمة الغرف", rooms: "خدمة الغرف", technical: "صيانة", reception: "الاستقبال", fnb: "مطعم", laundry: "غسيل", transportation: "نقل", spa: "سبا", other: "استقبال / أخرى", minibar: "ميني بار" },
};

export const DEPT_ICONS = {
  housekeeping: Sparkles, rooms: Sparkles, technical: Wrench, reception: Bell,
  fnb: Utensils, laundry: Shirt, transportation: Car, spa: Heart, other: Bell, minibar: Beer
};
